### PR TITLE
Ensure stacktrace is parsed correctly

### LINKED ISSUE #9059: Allow extensions to pass their display names when registering themselves using the registerRemoteServerProvider()
We could pass a display name variable in the JupyterUriProvider which is passed in the registerRemoteServerProvider() api of the Jupyter extension. This can then be shown in the description of the quick picks rather than something like "ms-toolsai.vscode-ai"

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9059

### CODE REVIEW

File: src/client/common/application/extensions.ts [hunk 1]
```diff
@@ -40,6 +41,12 @@ export class Extensions implements IExtensions {
                     }
                 })
                 .filter((item) => item && !item.toLowerCase().startsWith(jupyterExtRoot)) as string[];
+            stacktrace.parse(new Error('Ex')).forEach((item) => {
```
Comment (DonJayamanne) [inline src/client/common/application/extensions.ts:44]: The stack trace can also be `at xyx.js:123:12` and this doesn't match the regex.
I've left the regex in case that cases some other edge cases and added the use of the package which should be more accurate and cover the other cases we haven't handled with our regex. (not going to fix the regex, as the package would be more accurate)

FYI - this is a breaking change for AML extension

**Review by IanMatthewHuff — APPROVED** [review]

File: src/client/common/application/extensions.ts (hunk 1 above)
Comment (DonJayamanne) [reply src/client/common/application/extensions.ts:44]: Oops, should remove that `Ex`

Comment (DonJayamanne) [reply src/client/common/application/extensions.ts:44]: Not required.

**Review by rchiodo — APPROVED** [review]
