### PR TITLE
Fix for issue #11396

### LINKED ISSUE #11396: Cell debug doesn't stop at breakpoints when VSCode is run on Windows but a remote kernel runs on Unix
## Environment data

-   VS Code version: 1.71.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.8.1002431955
-   Python Extension version (available under the Extensions sidebar): v2022.14.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise 19044.1889
-   Python and/or Anaconda version: Python 3.9.12, Anaconda 4.14.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

After setting a breakpoint in a Jupyter Notebook cell and clicking on Debug cell, the debugger should stop at the breakpoint and show runtime info.

## Actual behaviour

Instead of stopping on the breakpoint, VSCode simply executes the cell. The behavior is due to a bug in the kernelDebugAdapter, see later.

## Steps to reproduce:

Start VSCode on a Windows machine and connect to a kernel that runs for example on Ubuntu (or some other unix system), then try debugging a cell.

## Logs

The issue was evident from the debugpy logs on the server. In a nutshell: even though the kernel was running on unix, the SetBreakpoint requests included paths of the form "\tmp\kernel_id\dumped_cell_content_id.py", and the responses were File Not Found exceptions - as it could be expected.

## Solution

The problem stems from path normalization in the dumpCell function of the kernelDebugAdapter. It normalizes the path based on the OS where VSCode runs, which doesn't necessarily coincide with the OS where the kernel runs. The normalization is unnecessary, as on the VSCode side the path on the kernel is simply a key in a hashmap - it works just as fine with whatever path the kernel returned, but in return when VSCode sends the path back to the kernel this way it's guaranteed that the path exists.

I'll be sending a pull-request with the solution when the change passes the CI.

### PR DESCRIPTION
**Pull request by adam-zlatniczki**
* During notebook cell debugging, apply path normalization on the path of the dumped tmp file only if the kernel runs on a Windows machine.

Fixes #11396

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [x] Has sufficient logging.
-   [x] Has telemetry for feature-requests.
-   [x] Unit tests & system/integration tests are added/updated.
-   [x] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [x] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/notebooks/debugger/kernelDebugAdapter.ts [hunk 1]
```diff
@@ -22,7 +22,18 @@ export class KernelDebugAdapter extends KernelDebugAdapterBase {
...
                 code: cell.document.getText().replace(/\r\n/g, '\n')
             });
-            const norm = path.normalize((response as IDumpCellResponse).sourcePath);
+
+            // Based on the response, check if the kernel runs on a Unix or Windows machine.
+            // If it runs on Windows, then path normalization might be necessary
+            // (see https://github.com/ipython/ipykernel/issues/995).
+            const dumpFilePathOnKernelSide = (response as IDumpCellResponse).sourcePath;
+            var norm = '';
+            if (dumpFilePathOnKernelSide.match('[A-Za-z]:.*')) {
```
Comment (roblourens) [inline src/notebooks/debugger/kernelDebugAdapter.ts:31]: A reusable utility for this would be nice, with a couple tests. It should also only match that pattern at the beginning of the string, and the pattern should be a regex literal.

File: src/notebooks/debugger/kernelDebugAdapter.ts [hunk 2]
```diff
@@ -22,7 +22,18 @@ export class KernelDebugAdapter extends KernelDebugAdapterBase {
             const response = await this.session.customRequest('dumpCell', {
                 code: cell.document.getText().replace(/\r\n/g, '\n')
             });
-            const norm = path.normalize((response as IDumpCellResponse).sourcePath);
+
+            // Based on the response, check if the kernel runs on a Unix or Windows machine.
+            // If it runs on Windows, then path normalization might be necessary
+            // (see https://github.com/ipython/ipykernel/issues/995).
+            const dumpFilePathOnKernelSide = (response as IDumpCellResponse).sourcePath;
+            var norm = '';
```
Comment (roblourens) [inline src/notebooks/debugger/kernelDebugAdapter.ts:30]: You can use `let`, we don't use `var` anymore

File: src/notebooks/debugger/kernelDebugAdapter.ts [hunk 3]
```diff
@@ -22,7 +22,18 @@ export class KernelDebugAdapter extends KernelDebugAdapterBase {
...
+            if (dumpFilePathOnKernelSide.match('[A-Za-z]:.*')) {
+                norm = path.normalize(dumpFilePathOnKernelSide);
```
Comment (roblourens) [inline src/notebooks/debugger/kernelDebugAdapter.ts:32]: normalize would have the same cross-OS problem here. If you know it's a windows path then you could do `path.win32.normalize` or write a simpler function for the slashes

**Comment by adam-zlatniczki** [comment]
Hi Rob, sorry for the late response, I was quite occupied the last week or so. I've introduced some changes based on your comments. I was wondering a bit about where such a utility function would fit well. As I see it, this kind of functionality is only expected to be used in kernel debug adapters, so I decided to make it available as a static method of the KernelDebugAdapterBase class instead of putting it into the general path utilities. If you think it would be better the other way, then I can move the function and the unit tests to the path library.

**Review by joyceerhl — APPROVED** [review]

**Comment by jersonchua** [comment]
I see that the fix was reverted. I'm seeing the same issue reported in https://github.com/microsoft/vscode-jupyter/issues/11396
 How can I address it? VSCode is running in windows and the kernel is running in a Linux container.
 
Jupyter Extension version:  v2023.11.1003402403
ipykernel: 6.20.2
debugpy: 1.80
python: 3.10.2

Here are some relevant logs. 

**sourcePath in dumpCell has forward slash**
2024-08-09 15:01:14.644 info: < {"header": {"msg_id": "491ec245-2cadc611fe3575525aa4b73a_338_103", "msg_type": "debug_reply", "username": "glue_user", "session": "491ec245-2cadc611fe3575525aa4b73a", "date": "2024-08-09T19:01:14.570370Z", "version": "5.3"}, "msg_id": "491ec245-2cadc611fe3575525aa4b73a_338_103", "msg_type": "debug_reply", "parent_header": {"date": "2024-08-09T19:01:14.093000Z", "msg_id": "21d47a00-7e31-4fea-b50b-b03e371a1bc5", "msg_type": "debug_request", "session": "bdc61c4a-6655-4165-bfc7-0e1360b7751e", "username": "", "version": "5.2"}, "metadata": {}, "content": {"type": "response", "request_seq": 15, "success": true, "command": "dumpCell", "body": {"sourcePath": "**/tmp/ipykernel_338/2523026605.py**"}}, "buffers": [], "channel": "control"}


**path in setBreakpoints has back slash. I think this is caused by the path normalization logic in the extension.**
2024-08-09 15:01:14.662 info: > {"buffers":[],"channel":"control","content":{"seq":10,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"Untitled-1.ipynb","path":"**\\tmp\\ipykernel_338\\2523026605.py**"},"lines":[2],"breakpoints":[{"line":2}],"sourceModified":false}},"header":{"date":"2024-08-09T19:01:14.662Z","msg_id":"c5f0353e-a3d8-4cdf-b14c-df854ef4c0ae","msg_type":"debug_request","session":"bdc61c4a-6655-4165-bfc7-0e1360b7751e","username":"","version":"5.2"},"metadata":{},"parent_header":{}}

**And because the path is the back slash, the debugger returned "Breakpoint in file that does not exist"**
2024-08-09 15:01:14.737 info: < {"header": {"msg_id": "491ec245-2cadc611fe3575525aa4b73a_338_109", "msg_type": "debug_reply", "username": "glue_user", "session": "491ec245-2cadc611fe3575525aa4b73a", "date": "2024-08-09T19:01:14.669487Z", "version": "5.3"}, "msg_id": "491ec245-2cadc611fe3575525aa4b73a_338_109", "msg_type": "debug_reply", "parent_header": {"date": "2024-08-09T19:01:14.662000Z", "msg_id": "c5f0353e-a3d8-4cdf-b14c-df854ef4c0ae", "msg_type": "debug_request", "session": "bdc61c4a-6655-4165-bfc7-0e1360b7751e", "username": "", "version": "5.2"}, "metadata": {}, "content": {"seq": 25, "type": "response", "request_seq": 10, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"verified": false, "id": 1, "message": **"Breakpoint in file that does not exist."**, "source": {"name": "Untitled-1.ipynb", "path": **"\\tmp\\ipykernel_338\\2523026605.py"**}, "line": 2}]}}, "buffers": [], "channel": "control"}

Please let me know if there's any additional information I can provide. Thanks.

**Comment by adam-zlatniczki** [comment]
If I recall correctly, Rob mentioned something about the change breaking the CI for the browser-based VSCode frontend, that's why it had to be reverted. Since I moved to WSL I didn't face the Windows-Unix cross-OS issue anymore and forgot about this. Unfortunately I don't have time to pick up the work right now, but you can open a new Issue and refer this one.

**Comment by jersonchua** [comment]
@adam-zlatniczki i just opened a new issue: https://github.com/microsoft/vscode-jupyter/issues/15934

Thanks.
