### PR TITLE
Make sure to find active interpreter even with no folder

### LINKED ISSUE #8409: Syntax colorization for Python is incorrect in Notebookcells when no folder or active interpreter
* Latest Insiders
* Pylance 2021.11.2

**See below (latest insiders):** (this used to work in Insiders, see screenshots here https://github.com/microsoft/vscode-jupyter/issues/8374) 

image

**Here's a screenshot from the stable version (hence a regression):**
image

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #8409

Active interpreter is possible without a folder. Make sure to support this case.

### CODE REVIEW

File: src/client/datascience/notebook/intellisense/intellisenseProvider.ts [hunk 1]
```diff
@@ -82,15 +84,16 @@ export class IntellisenseProvider implements INotebookLanguageClientProvider, IE
         const folder =
             this.workspaceService.getWorkspaceFolder(fsPath ? Uri.file(fsPath) : undefined)?.uri ||
             (this.workspaceService.rootPath ? Uri.file(this.workspaceService.rootPath) : undefined);
-        if (folder && !this.activeInterpreterCache.has(folder.fsPath)) {
+        const key = folder ? folder.fsPath : EmptyWorkspaceKey;
```
Comment (DonJayamanne) [inline src/client/datascience/notebook/intellisense/intellisenseProvider.ts:87]: Can't this be an empty string? I'd feel more comfortable with an empty string than using some other hardcoded values.

**Review by DonJayamanne — APPROVED** [review]

File: src/client/datascience/notebook/intellisense/intellisenseProvider.ts (hunk 1 above)
Comment (rchiodo) [reply src/client/datascience/notebook/intellisense/intellisenseProvider.ts:87]: Sure. i don't think it matters.
