### PR TITLE
Fix password validations with jupyter server selection

### LINKED ISSUE #10300: Jupyter server with incorrect password validates too late
1. start an external juptyer server with a password
2. Specify server for connections in VS Code and use that server with the wrong password

Expected:
Error message that connection did not succeed

Actual:
The prompt goes away without any notification, but no connection was made.
Next time you try to connect to the server, no password prompt appears, but the connection fails because the (saved) password is wrong.

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #10300 

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [x] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [x] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/kernels/jupyter/launcher/jupyterPasswordConnect.ts [hunk 1]
```diff
@@ -51,7 +52,15 @@ export class JupyterPasswordConnect implements IJupyterPasswordConnect {
         // See if we already have this data. Don't need to ask for a password more than once. (This can happen in remote when listing kernels)
         let result = this.savedConnectInfo.get(newUrl);
         if (!result) {
-            result = this.getNonCachedPasswordConnectionInfo(newUrl);
+            result = this.getNonCachedPasswordConnectionInfo(newUrl).then((value) => {
+                // If we fail to get a valid password connect info, don't save the value
+                traceInfo(`Password for ${newUrl} was invalid.`);
+                if (!value) {
+                    this.savedConnectInfo.delete(newUrl);
```
Comment (IanMatthewHuff) [inline src/kernels/jupyter/launcher/jupyterPasswordConnect.ts:59]: This fixes the main issue. The connection info was getting saved regardless of if we validated it or now. So if you entered an incorrect password it will continue to use that for the same VS Code session without a chance to fix it.

File: src/platform/common/utils/multiStepInput.ts [hunk 2]
```diff
@@ -266,6 +266,9 @@ export class MultiStepInput<S> implements IMultiStepInput<S> {
                             resolve(inputValue);
                         } else {
                             input.validationMessage = validationMessage;
+
+                            // On validation error make sure we are showing our input
+                            input.show();
```
Comment (IanMatthewHuff) [inline src/platform/common/utils/multiStepInput.ts:271]: Smaller fix here, with the new validation flow the main validation all happens with the server selection multistep input. But when coming back from the failed password validation the server selection input was not actually getting shown again (this was exposed by fixing the bug again). Make sure we show our input again so the customer can see the password error.

**Comment by IanMatthewHuff** [comment]
Note, Rich's experimental new UI has changed the flow here some. In the old UI you'll see the validation message and get another chance to hit enter on the URL entry dialog. In the new experimental UI flow you'll get a modal warning dialog about the password failure, but in both cases you'll get a chance to re-input a failed password.

File: src/test/datascience/mockInputBox.ts [hunk 3]
```diff
@@ -38,27 +41,31 @@ export class MockInputBox implements InputBox {
         return this.didHideEmitter.event;
     }
     public show(): void {
-        // After 10 ms set the value, then accept it
-        setTimeout(() => {
-            this.value = this._value;
-            this.didChangeValueEmitter.fire(this._value);
+        // Unless we have specified more, we only want to fire the input one time (in case show is called more)
```
Comment (IanMatthewHuff) [inline src/test/datascience/mockInputBox.ts:44]: Tweak to get unit tests working. Due to the validation change above show can be called more often. Show has been rigged in the mock to input and fire the value as if a user entered it. Instead, just do it once (with the option for more for one test that expected to call it multiple times with user input).

File: src/test/datascience/jupyterPasswordConnect.unit.test.ts [hunk 4]
```diff
@@ -227,6 +233,101 @@ suite('JupyterPasswordConnect', () => {
         fetchMock.verifyAll();
     });
 
+    test('getPasswordConnectionInfo bad password followed by good password.', async () => {
```
Comment (IanMatthewHuff) [inline src/test/datascience/jupyterPasswordConnect.unit.test.ts:236]: New test to make sure that we don't cache a failed password.

File: src/test/datascience/jupyterPasswordConnect.unit.test.ts [hunk 5]
```diff
@@ -117,6 +117,7 @@ suite('JupyterPasswordConnect', () => {
     }
 
     test('getPasswordConnectionInfo', async () => {
+        when(appShell.showInputBox(anything())).thenReturn(Promise.resolve('Python'));
```
Comment (IanMatthewHuff) [inline src/test/datascience/jupyterPasswordConnect.unit.test.ts:120]: Updated previous good password check to also actually check the password in the fetch.

**Comment by IanMatthewHuff** [comment]
There are a couple of test failures, the run by line debugging ones look unrelated, but I'll check it out before pushing.

**Review by DonJayamanne — APPROVED** [review]

**Comment by IanMatthewHuff** [comment]
Test failures look to just be #11137 so pushing.
