### PR TITLE
Stop using debugConfiguration.python

### LINKED ISSUE #10789: Exception when view value in data viewer
## Environment data

-   VS Code version: 1.69.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.6.1101950301
-   Python Extension version (available under the Extensions sidebar): v2022.10.0
-   OS (Windows | Mac | Linux distro) and version: ubuntu22.04 wsl2
-   Python and/or Anaconda version: python3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Remote (wsl)

## Actual behaviour

when i'm debugging my project and i click **view value in data viewer**, it happend error 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.69.1, wsl, desktop)
Jupyter Extension Version: 2022.6.1101950301.
Python Extension Version: 2022.10.0.
Multiple Workspace folders opened ...
info 13:51:14.611: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 13:51:16.499: LSP Notebooks experiment is disabled -- not in treatment group
info 13:51:17.651: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 13:51:18.915: Process Execution: > ~/.pyenv/versions/3.8.6/envs/Risk_py38/bin/python -m pip list
> ~/.pyenv/versions/3.8.6/envs/Risk_py38/bin/python -m pip list
info 13:54:18.889: Found debugAdapterPython on Debug Configuration to use
error 13:54:18.892: [TypeError: t.startsWith is not a function
	at C.getDebugAdapterPython (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:274390)
	at C.onVariablePanelShowDataViewerRequest (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:273113)
	at C.<anonymous> (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:24:464889)
	at o._executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at f._processReadQueue (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:21271)
	at f.acceptFrame (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:20927)
	at v._acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:18891)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:15880
	at Socket.R (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)]
warn 13:54:18.893: DataScience Error [TypeError: t.startsWith is not a function
	at C.getDebugAdapterPython (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:274390)
	at C.onVariablePanelShowDataViewerRequest (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:273113)
	at C.<anonymous> (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:24:464889)
	at o._executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at f._processReadQueue (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:21271)
	at f.acceptFrame (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:20927)
	at v._acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:18891)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:15880
	at Socket.R (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)]

```

</p>
</details>

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #10789 

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts [hunk 1]
```diff
@@ -147,7 +147,7 @@ export class DataViewerCommandRegistry implements IExtensionSingleActivationServ
         }
 
         if (pythonPath) {
-            let untildePath = debugConfiguration.python;
+            let untildePath = pythonPath;
```
Comment (IanMatthewHuff) [inline src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:150]: Just a mess up on my part when I touched this last :(. The goal was to not look at .python anymore as it's often, but not always the path. But I accidentally left this in. 

I added an E2E test for the positive case here already, and I don't see a need for a specific regression tests as it would just be passing in a malformed .python, which at this point isn't any different from any other property on the debugConfiguration which we don't look at.

**Review by rchiodo — APPROVED** [review]

**Comment by rchiodo** [comment]
Do we want to hot fix this?

**Comment by sadasant** [comment]
cc: @IanMatthewHuff ^

**Comment by IanMatthewHuff** [comment]
@rchiodo @sadasant Yeah, I think so. It's low danger fix and a number of folks hit this before. I'll start the process.
