### PR TITLE
Fixes to debugging of IW on web with remote kernels

### LINKED ISSUE #10920: web - IW debugging cannot find the file to debug
1. go to insider.code.dev
2. connect to a remote jupyter server
3. create a python file with a `# %%` cell and save it
4. click the debug cell code lens

actual:
the cell starts running, but instead of breaking in the file, a new editor opens with error message:
`Could not load source '<ipython-input-1-022d05bbd8a8>': source unavailable.`

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #10920

### CODE REVIEW

File: src/interactive-window/debugger/startupCodeProvider.ts [hunk 1]
```diff
@@ -32,6 +32,11 @@ export class InteractiveWindowDebuggingStartupCodeProvider implements IStartupCo
         }
 
         if (kernel.notebook?.notebookType === InteractiveWindowView) {
+            if (!isLocalConnection(kernel.kernelConnectionMetadata)) {
+                // With remove kernel connection in the web, we use the new approach, i.e. Jupyter debugger protocol.
```
Comment (DonJayamanne) [inline src/interactive-window/debugger/startupCodeProvider.ts:36]: This was missing in the refactoring that was done here https://github.com/microsoft/vscode-jupyter/pull/10853

**Review by rebornix — APPROVED** [review]

**Review by sadasant — APPROVED** [review]
