### PR TITLE
Fix: Prompting for password in for remote jupyter

### LINKED ISSUE #13000: Input passwork UI does not work
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

After activating a remote server, I tried to connect to the server using the kernel. However, the input password UI or form just flashes out, remaining only 0.1s. As a result, the connection was refused.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #13000

### CODE REVIEW

File: src/kernels/jupyter/connection/jupyterPasswordConnect.ts [hunk 1]
```diff
@@ -61,6 +68,12 @@ export class JupyterPasswordConnect implements IJupyterPasswordConnect {
 
                 return value;
             });
+            result.finally(() => {
+                deferred.resolve();
```
Comment (DonJayamanne) [inline src/kernels/jupyter/connection/jupyterPasswordConnect.ts:72]: As soon as the password input is displayed this gets hidden
Then we go back to the multi-select quick pick and the password input gets dismissed

File: src/kernels/jupyter/jupyterUtils.ts [hunk 2]
```diff
@@ -127,8 +129,11 @@ export function createRemoteConnectionInfo(
         dispose: noop,
         rootDirectory: Uri.file(''),
         workingDirectory: serverUri?.workingDirectory,
-        getAuthHeader: serverUri ? () => getJupyterServerUri(uri)?.authorizationHeader : undefined,
-        getWebsocketProtocols: serverUri ? () => getJupyterServerUri(uri)?.webSocketProtocols || [] : () => [],
+        // For remote jupyter servers that are managed by us, we can provide the auth header.
+        // Its crucial this is set to undefined, else password retrieval will not be attempted.
+        getAuthHeader: serverUri && !serverId.startsWith('_builtin') ? () => serverUri?.authorizationHeader : undefined,
```
Comment (DonJayamanne) [inline src/kernels/jupyter/jupyterUtils.ts:134]: This resulted in auth never working, even after entering the password it would never authenticate against the server

File: src/standalone/userJupyterServer/userServerUrlProvider.ts [hunk 3]
```diff
@@ -268,9 +270,19 @@ export class UserJupyterServerUrlProvider implements IExtensionSyncActivationSer
...
                     if (message) {
+                        if (inputWasHidden) {
+                            input.show();
+                        }
                         input.validationMessage = message;
                     } else {
-                        const serverInfo = this.parseUri(uri);
+                        // // Offer the user a chance to pick a display name for the server
+                        // // Leaving it blank will use the URI as the display name
+                        // const displayName = await this.applicationShell.showInputBox({
```
Comment (DonJayamanne) [inline src/standalone/userJupyterServer/userServerUrlProvider.ts:280]: Left for now, for future reference.

File: src/standalone/userJupyterServer/userServerUrlProvider.ts [hunk 4]
```diff
@@ -286,7 +298,10 @@ export class UserJupyterServerUrlProvider implements IExtensionSyncActivationSer
                     }
                 }),
                 input.onDidHide(() => {
-                    resolve(undefined);
+                    inputWasHidden = true;
```
Comment (DonJayamanne) [inline src/standalone/userJupyterServer/userServerUrlProvider.ts:301]: As soon as the password input is displayed this gets hidden
Then we go back to the multi-select quick pick and the password input gets dismissed

File: src/standalone/userJupyterServer/userServerUrlProvider.ts [hunk 5]
```diff
@@ -306,16 +321,17 @@ export class UserJupyterServerUrlProvider implements IExtensionSyncActivationSer
             const baseUrl = `${url.protocol}//${url.host}${url.pathname === '/lab' ? '' : url.pathname}`;
 
             const token = `${url.searchParams.get('token')}`;
```
Comment (DonJayamanne) [inline src/standalone/userJupyterServer/userServerUrlProvider.ts:323]: we were unnecessarily storing the text `null` and passing that around, instead of using an `empty string` or `undefined`

File: src/kernels/jupyter/connection/serverSelector.ts [hunk 6]
```diff
@@ -104,6 +105,8 @@ export async function validateSelectJupyterURI(
             if (!handled) {
                 return DataScience.jupyterSelfCertExpiredErrorMessageOnly;
             }
+        } else if (err && err instanceof JupyterInvalidPasswordError) {
+            return DataScience.passwordFailure;
```
Comment (DonJayamanne) [inline src/kernels/jupyter/connection/serverSelector.ts:109]: We now have a better error message

**Review by rebornix — APPROVED** [review]
