### PR TITLE
Fix remote tests

### LINKED ISSUE #9861: Remote tests are no longer using the Remote Jupyter kernels for tests
All tests are using local Python kernels for tests.
Explains why https://github.com/microsoft/vscode-jupyter/issues/9859

I guess this is blocked on https://github.com/microsoft/vscode-jupyter/issues/9834
Either way this is a change that's causing the tests to run against the wrong kernel.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9861

### CODE REVIEW

File: src/notebooks/controllers/notebookControllerManager.ts [hunk 1]
```diff
@@ -506,10 +506,13 @@ export class NotebookControllerManager implements INotebookControllerManager, IE
             // Don't attempt preferred kernel search for interactive window, but do make sure we
             // load all our controllers for interactive window
             const notebookMetadata = getNotebookMetadata(document);
-            if (document.notebookType === JupyterNotebookView) {
-                const resourceType = getResourceType(document.uri);
-                const isPythonNbOrInteractiveWindow =
-                    isPythonNotebook(notebookMetadata) || resourceType === 'interactive';
+            const resourceType = getResourceType(document.uri);
+            const isPythonNbOrInteractiveWindow = isPythonNotebook(notebookMetadata) || resourceType === 'interactive';
+            if (document.notebookType === JupyterNotebookView && !this.isLocalLaunch && isPythonNbOrInteractiveWindow) {
```
Comment (DonJayamanne) [inline src/notebooks/controllers/notebookControllerManager.ts:511]: When dealing with remotes, always give preference to remote kernels, 
This is how it used to work, 

Basically reverting to previous behavior to enur tests pass successfully.
Changes to this can be made here along with the fixes to the tests https://github.com/microsoft/vscode-jupyter/issues/9834

**Review by rchiodo — APPROVED** [review]

**Review by amunger — APPROVED** [review]
