### PR TITLE
When the remote server is actually 'localhost' we can behave better ...

### LINKED ISSUE #1551: If on 'http://localhost', the notebookFileRoot should still be used
Specify a remote server URI that's local
Open a notebook that would be local to that host
Run this code:
```
import os
os.getcwd()
```

Expected result:
Root of notebook

Actual result:
Workspace root.

This is because we skip changing the directory of the kernel when the server URI is set. We could instead set this whenever the server URI is local.

### LINKED ISSUE #8285: Intellisense stop working the moment it connects to remote jupyter server
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: windows 10
-   Python and/or Anaconda version: Python 3.8.10 (locally); 3.8.8 in wsl2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote - WSL2 ubuntu 20

## Expected behaviour

Open a notebook and see IntelliSense underlying missing variable, highlighting import not used and other functionalities.

## Actual behaviour

Nothing happens and features are not appearing, text is all same colours

## Steps to reproduce:

Launch jupyter server on wsl2 terminal.
Open VScode and open a notebook; at that stage the notebook has IntelliSense working (I can see different colours for example)
click on yes to connect to remote server
no more colours or info in the notebook

1. What happens
Before
image
Open dialogue
image
Click yes, then this is what is displayed:
image

## Logs

Not sure if it's all of it:

[2021-11-17 15:28:30.565] [exthost] [info] Extension host with pid 47272 started
[2021-11-17 15:28:30.566] [exthost] [info] Skipping acquiring lock for c:\Users\user\AppData\Roaming\Code\User\workspaceStorage\3377dadeb7f1f6022e096e6aa1b5a108.
[2021-11-17 15:28:31.000] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-11-17 15:28:31.015] [exthost] [info] ExtensionService#_doActivateExtension amazonwebservices.aws-toolkit-vscode, startup: false, activationEvent: 'onLanguage:python'
[2021-11-17 15:28:31.295] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.vscode-pylance
[2021-11-17 15:28:31.368] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
[2021-11-17 15:28:31.470] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:python'
[2021-11-17 15:28:31.515] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebook:jupyter-notebook}'
[2021-11-17 15:28:31.523] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2021-11-17 15:28:31.531] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*', root cause: atlassian.atlascode
[2021-11-17 15:28:31.555] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: true, activationEvent: '*', root cause: atlassian.atlascode
[2021-11-17 15:28:31.750] [exthost] [info] ExtensionService#_doActivateExtension Oracle.oracledevtools, startup: true, activationEvent: '*'
[2021-11-17 15:28:32.930] [exthost] [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme, startup: true, activationEvent: '*'
[2021-11-17 15:28:33.578] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2021-11-17 15:28:33.676] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2021-11-17 15:28:33.687] [exthost] [info] ExtensionService#_doActivateExtension atlassian.atlascode, startup: true, activationEvent: '*'
[2021-11-17 15:28:33.908] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2021-11-17 15:28:33.965] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-17 15:28:33.976] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-17 15:28:34.003] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2021-11-17 15:28:34.057] [exthost] [info] Eager extensions activated
[2021-11-17 15:28:34.184] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-11-17 15:28:34.236] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2021-11-17 15:28:34.246] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
[2021-11-17 15:28:34.285] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2021-11-17 15:28:34.328] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2021-11-17 15:28:34.375] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
[2021-11-17 15:28:36.248] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'api', root cause: ms-python.python
[2021-11-17 15:28:38.642] [exthost] [info] ExtensionService#_doActivateExtension mechatroner.rainbow-csv, startup: false, activationEvent: 'onLanguage:plaintext'

## Infos
This was working fine few weeks ago, but I don't know what changed to have the behaviour now.

Thank you

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #8285 
Fixes #1551 

Special case some scenarios to act like local when the server is 'localhost' or '127.0.0.1'

Also fix remote intellisense to work in those scenarios or in true remote.

### CODE REVIEW

File: src/client/datascience/jupyter/kernels/jupyterKernelService.ts [hunk 1]
```diff
@@ -66,7 +66,12 @@ export class JupyterKernelService {
         var specFile: string | undefined = undefined;
 
         // If the spec file doesn't exist or is not defined, we need to register this kernel
-        if (kernel.kind !== 'connectToLiveKernel' && kernel.kernelSpec && kernel.interpreter) {
+        if (
+            kernel.kind !== 'connectToLiveKernel' &&
+            kernel.kind != 'startUsingRemoteKernelSpec' &&
```
Comment (IanMatthewHuff) [inline src/client/datascience/jupyter/kernels/jupyterKernelService.ts:71]: missing =?

Comment (rchiodo) [reply src/client/datascience/jupyter/kernels/jupyterKernelService.ts]: Yep. Thanks. Which also prompted me to lookup the difference. ```===``` does not do any type manipulation and just compares the values. ```==``` will convert the values to the same types. So I guess ```===``` is faster.

**Review by IanMatthewHuff — APPROVED** [review]

File: src/client/datascience/jupyter/kernels/types.ts [hunk 2]
```diff
@@ -112,6 +113,14 @@ export function isLocalConnection(
     );
 }
 
+export function isLocalHostConnection(kernelConnection: KernelConnectionMetadata): boolean {
+    if (kernelConnection.kind === 'connectToLiveKernel' || kernelConnection.kind === 'startUsingRemoteKernelSpec') {
+        const parsed = new url.URL(kernelConnection.baseUrl);
+        return parsed.hostname.toLocaleLowerCase() === 'localhost' || parsed.host === '127.0.0.1';
```
Comment (IanMatthewHuff) [inline src/client/datascience/jupyter/kernels/types.ts:119]: I was going to ask if localhost is more configurable, and I believe it is. But I think that we only have to worry about how Jupyter starts it, so this is fine I believe.

Comment (IanMatthewHuff) [reply src/client/datascience/jupyter/kernels/types.ts:119]: Was going to ask if we needed to check for an npm module or something for a more comprehensive loopback check, but I don't think we need to.

File: src/client/datascience/errors/errorHandler.ts [hunk 3]
```diff
@@ -443,7 +447,11 @@ export class DataScienceErrorHandler implements IDataScienceErrorHandler {
         if (!cellToDisplayErrors) {
             return;
         }
-        if (kernelConnection.kind === 'connectToLiveKernel' || !kernelConnection.interpreter) {
+        if (
+            kernelConnection.kind === 'connectToLiveKernel' ||
+            kernelConnection.kind === 'startUsingRemoteKernelSpec' ||
+            !kernelConnection.interpreter
+        ) {
```
Comment (DonJayamanne) [inline src/client/datascience/errors/errorHandler.ts:454]: Oops, btw, what was the error you ran into.

File: src/client/datascience/jupyter/kernels/jupyterKernelService.ts [hunk 4]
```diff
@@ -59,14 +59,23 @@ export class JupyterKernelService {
         const token = wrapCancellationTokens(cancelToken, tokenSource.token);
 
         // If we have an interpreter, make sure it has the correct dependencies installed
-        if (kernel.kind !== 'connectToLiveKernel' && kernel.interpreter) {
+        if (
+            kernel.kind !== 'connectToLiveKernel' &&
+            kernel.interpreter &&
+            kernel.kind !== 'startUsingRemoteKernelSpec'
+        ) {
```
Comment (DonJayamanne) [inline src/client/datascience/jupyter/kernels/jupyterKernelService.ts:66]: Shoot even more, yup, i think i know what would have happened...
Thanks

Comment (rchiodo) [reply src/client/datascience/jupyter/kernels/jupyterKernelService.ts:66]: No these are my fault. A remote kernel couldn't have an interpreter until my change. So your old if statement would have worked.

**Review by DonJayamanne — APPROVED** [review]

File: src/test/datascience/notebook/helper.ts [hunk 5]
```diff
@@ -344,7 +344,7 @@ export async function waitForKernelToGetAutoSelected(expectedLanguage?: string,
                 );
                 return preferred != undefined;
             },
-            3_000,
+            30_000,
```
Comment (rchiodo) [inline src/test/datascience/notebook/helper.ts:347]: This timeout was failing because now remote connections try to match interpreters. Getting intepreter details was taking longer than 3 seconds.

Comment (rchiodo) [reply src/test/datascience/notebook/helper.ts:347]: This is what was causing my test failures AFAIK. Hopefully next run completes fully.
