### PR TITLE
Fix API not being allowed in stable

### LINKED ISSUE #9868: Jupyter Powertoys not completely working on candidate April Release of VS Code
- Install candidate release of vscode from https://builds.code.visualstudio.com/builds/stable
- Install candidate release of jupyter extension from https://dev.azure.com/monacotools/Monaco/_build/results?buildId=169234&view=artifacts&pathAsName=false&type=publishedArtifacts.
- Install the Powertoys extension from the Marketplace

Neither the contextual help nor the kernal management feature will work. Execution groups do work though.

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #9868

### CODE REVIEW

File: src/platform/api/apiAccessService.ts [hunk 1]
```diff
@@ -46,11 +46,6 @@ export class ApiAccessService {
             }
             return { extensionId: info.extensionId, accessAllowed: true };
         }
-        // For now, this API is only available in insiders.
```
Comment (rchiodo) [inline src/platform/api/apiAccessService.ts:49]: If we want powertoys to work, we have to allow insiders. Was thinking might just special case power toys, but we already have an allowed list so seemed redundant.

**Review by greazer — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]
