### PR TITLE
Hide Python Getting Started page in the Install Extension workflow

### LINKED ISSUE #10793: Hide the Python getting started page when installing Python Extension via the Kernel Picker command
Repro steps.

1. Uninstall the Python Extension
2. Reload the Window
3. In the kernel picker select the "Install Python Extension" command
4. The Python getting started page pops up

Considered part of #6886 flow.

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #10793

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/notebooks/controllers/commands/installPythonControllerCommands.ts [hunk 1]
```diff
@@ -177,8 +171,7 @@ export class InstallPythonControllerCommands implements IExtensionSingleActivati
             // Now start to indicate that we are performing the install and locating kernels
             const reporter = this.progressReporter.createProgressIndicator(DataScience.installingPythonExtension());
             try {
-                // Directly install the python extension
-                await this.commandManager.executeCommand('workbench.extensions.installExtension', PythonExtension);
+                await this.extensionChecker.directlyInstallPythonExtension();
```
Comment (IanMatthewHuff) [inline src/notebooks/controllers/commands/installPythonControllerCommands.ts:174]: I had added a helper function before and forgot to use it, so swapped it in now.

**Review by rchiodo — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]
