### PR TITLE
Fix failing nbconvert CI test by generating a proper temp ipynb file

### LINKED ISSUE #11190: Export a basic notebook document with nbconvert test is failing
Failing on Insiders builds consistently. 

image

These two builds only. From this change:
https://github.com/microsoft/vscode-jupyter/runs/7959359559?check_suite_focus=true

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #11190 

Working on getting branch all green for release.

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [x] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/test/datascience/notebook/helper.ts [hunk 1]
```diff
@@ -251,13 +251,11 @@ export async function createTemporaryNotebook(
     const data: nbformat.INotebookContent = {
         cells,
         metadata: {
-            orig_nbformat: 4
+            orig_nbformat: 4,
+            kernelspec: kernelSpec
         },
         nbformat: 4,
-        nbformat_minor: 2,
-        kernel: {
```
Comment (IanMatthewHuff) [inline src/test/datascience/notebook/helper.ts:258]: This is an invalid INotebookContent and nbconvert wasn't liking the <kernel> entry.

**Comment by IanMatthewHuff** [comment]
Initial run of tests cleared the nbconvert failures, but I did see one failure with:
remote, nonConda, 3.9, desktop, ubuntu-latest - Kernel Event - Kernel Events 

So trying a quick re-run to see if that is still there.

**Review by DonJayamanne — APPROVED** [review]
