### PR TITLE
Fix: Prompting for password in for remote jupyter (#13008)

### LINKED ISSUE #13000: Input passwork UI does not work
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

After activating a remote server, I tried to connect to the server using the kernel. However, the input password UI or form just flashes out, remaining only 0.1s. As a result, the connection was refused.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #13000

### CODE REVIEW

**Review by joyceerhl — CHANGES_REQUESTED** [review]
This seems like a clean cherry pick of the change that went into main, do we want to consider a more conservative fix for the release branch? cc @TylerLeonhardt

File: src/kernels/jupyter/jupyterUtils.ts [hunk 1]
```diff
@@ -128,8 +130,11 @@ export function createRemoteConnectionInfo(
         dispose: noop,
         rootDirectory: Uri.file(''),
         workingDirectory: serverUri?.workingDirectory,
-        getAuthHeader: serverUri ? () => getJupyterServerUri(uri)?.authorizationHeader : undefined,
-        getWebsocketProtocols: serverUri ? () => getJupyterServerUri(uri)?.webSocketProtocols || [] : () => [],
+        // For remote jupyter servers that are managed by us, we can provide the auth header.
+        // Its crucial this is set to undefined, else password retrieval will not be attempted.
+        getAuthHeader: serverUri && !serverId.startsWith('_builtin') ? () => serverUri?.authorizationHeader : undefined,
```
Comment (DonJayamanne) [inline src/kernels/jupyter/jupyterUtils.ts:135]: This change is required for things to work with the new kernle picker and remotes

**Review by joyceerhl — APPROVED** [review]

File: src/kernels/jupyter/serverSelector.ts [hunk 2]
```diff
@@ -104,6 +105,8 @@ export async function validateSelectJupyterURI(
             if (!handled) {
                 return DataScience.jupyterSelfCertExpiredErrorMessageOnly;
             }
+        } else if (err && err instanceof JupyterInvalidPasswordError) {
+            return DataScience.passwordFailure;
```
Comment (DonJayamanne) [inline src/kernels/jupyter/serverSelector.ts:109]: This change is required to get a proper error message when password is inavlid
None of this code path was tested, hence none of these things work with the new kernel picker
Hence the need for more changes

**Review by TylerLeonhardt — APPROVED** [review]
