### PR TITLE
Fix pylance timing out

### LINKED ISSUE #8906: Pylance can be slow in returning intellisense
I'm seeing this on a project with a single Notebook. @rchiodo mentioned opening an issue here and this one looks relevant.

**Environment**
OS: Windows 11 22000.466
VS Code: 1.64.0-Insiders
Jupyter: v2022.1.1001755318
Pylance: 0.18.1

**Logs**
https://gist.github.com/burkeholland/6f7deb0730456cc239db58c1eac8a59f

**Video**
https://user-images.githubusercontent.com/686963/151440515-cb083cb5-b08e-48ba-83b9-c4c1d523c206.mp4

**Project to reproduce**
https://github.com/claudiaregio/data-science

_Originally posted by @burkeholland in https://github.com/microsoft/pylance-release/issues/1338#issuecomment-1023623014_

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #8906 

Pylance can be slow and our jupyter completions were waiting for it to finish before returning any of the data the kernel might have.

This change maximizes that to 1 second.

### CODE REVIEW

File: src/client/datascience/notebook/intellisense/pythonKernelCompletionProvider.ts [hunk 1]
```diff
@@ -91,13 +91,14 @@ export class PythonKernelCompletionProvider implements CompletionItemProvider {
...
             parseInt(process.env.VSC_JUPYTER_IntellisenseTimeout || '0', 10) || Settings.IntellisenseTimeout;
+        const pylanceTimeout = Math.min(1000, timeout);
         traceInfoIfCI(`Notebook completion request for ${document.getText()}, ${document.offsetAt(position)}`);
         const [result, pylanceResults] = await Promise.all([
             waitForPromise(
                 this.getJupyterCompletion(kernel.session, document.getText(), document.offsetAt(position), token),
                 timeout
             ),
-            this.getPylanceCompletions(document, position, context, token)
+            waitForPromise(this.getPylanceCompletions(document, position, context, token), pylanceTimeout)
```
Comment (amunger) [inline src/client/datascience/notebook/intellisense/pythonKernelCompletionProvider.ts:101]: Could someone have a situation where it consistently takes just around that much time for pylance to return results? Would the result be that sometimes the completion list will contain pylance results and sometimes it doesn't?

File: src/client/datascience/notebook/intellisense/pythonKernelCompletionProvider.ts [hunk 2]
```diff
@@ -91,13 +91,14 @@ export class PythonKernelCompletionProvider implements CompletionItemProvider {
         // Allow slower timeouts for CI (testing).
         const timeout =
             parseInt(process.env.VSC_JUPYTER_IntellisenseTimeout || '0', 10) || Settings.IntellisenseTimeout;
+        const pylanceTimeout = Math.min(1000, timeout);
```
Comment (IanMatthewHuff) [inline src/client/datascience/notebook/intellisense/pythonKernelCompletionProvider.ts:94]: This feels a bit funny combined with a user controlled setting. If I specify 5000 for IntellisenseTimeout I think that I'd expect that to be the timeout, not 1000.

**Review by IanMatthewHuff — APPROVED** [review]
