### PR TITLE
Prompt to install ipykernel even after we fail the first time

### LINKED ISSUE #9444: Creating IW with a bad kernel and hitting cancel on the the ipykernel install allows for execution still
Testing #9435

If you cancel the ipykernel install the IW comes up correctly like so:

image

However you can still send code to it. 

It would be nice if it either
- Prevented sending anymore code
- Brought up the dialog again if you sent it again.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9444

& contains tests for this and the PR here https://github.com/microsoft/vscode-jupyter/pull/9455

I didn't want to pollute the other PR, hence this PR with just the new changes (easier for review)

### CODE REVIEW

File: src/interactive-window/editor-integration/codewatcher.ts [hunk 1]
```diff
@@ -1013,41 +1001,15 @@ export class CodeWatcher implements ICodeWatcher {
                 result = await interactiveWindow.addCode(code, file, line);
             }
         } catch (err) {
-            if (err instanceof InteractiveCellResultError) {
```
Comment (DonJayamanne) [inline src/interactive-window/editor-integration/codewatcher.ts:1016]: We no longer display errors in cells from code watcher.
The IW will display the errors in the cells.

File: src/interactive-window/interactiveWindow.ts [hunk 2]
```diff
@@ -78,11 +75,6 @@ export function getInteractiveCellMetadata(cell: NotebookCell): InteractiveCellM
     }
 }
 export class InteractiveWindow implements IInteractiveWindowLoadable {
-    public get ready() {
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:81]: Remove all of this, its much simpler now.
Relied on the factory class to create and provide all of he dependencies that wa y we don't end up with weird promises & nullable types.

File: src/interactive-window/interactiveWindow.ts [hunk 3]
```diff
@@ -95,35 +87,30 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
     public get submitters(): Uri[] {
         return this._submitters;
     }
-    public get notebookUri(): Uri | undefined {
-        return this._notebookDocument?.uri;
+    public get notebookUri(): Uri {
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:90]: Lots of nullable removed, it was actually impossible to have nullables, but we had it because of the way we structured the code. Now the editor is created outside in the factory class and injected into this.

nulls can be a pain.

File: src/interactive-window/interactiveWindow.ts [hunk 4]
```diff
@@ -132,144 +119,137 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
...
+                await this.deleteSysInfoCell(sysInfoCell);
+            } else {
+                // We don't have a cell when starting IW without an *.py file,
+                // hence display error where the sysinfo is displayed.
+                await this.finishSysInfoWithFailureMessage(ex, sysInfoCell);
             }
-        }
-    }
-
-    private async kernelEventHook(ev: 'willRestart' | 'willInterrupt') {
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:268]: Moved this to an internal fucntion so that its closer to the pre-restart and post re-start event handling.
It was a little weird to have some code inline and rest outside, was difficult to follow what was going on.

File: src/interactive-window/interactiveWindow.ts [hunk 5]
```diff
@@ -371,66 +346,17 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
         this.updateSysInfoMessage(message, true, cellPromise);
     }
 
-    private async finishWithFailureMessage(error: Error, cellPromise: Promise<NotebookCell | undefined>) {
+    private async finishSysInfoWithFailureMessage(error: Error, cellPromise: Promise<NotebookCell>) {
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:349]: Split the finishSysInfo message into two, one for success and one for failures, was a little weird to have a union of IKernel and Error, and then look for `info` to determine which is which

File: src/interactive-window/interactiveWindow.ts [hunk 6]
```diff
@@ -371,66 +346,17 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
...
-        const preferredController = connection
-            ? this.notebookControllerManager.getControllerForConnection(connection, 'interactive')
-            : await this.notebookControllerManager.getActiveInterpreterOrDefaultController(
-                  InteractiveWindowView,
-                  this.owner
-              );
-        return preferredController;
-    }
-
-    private async createEditor(preferredController: VSCodeNotebookController | undefined): Promise<NotebookEditor> {
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:393]: Bye bye, moved into factory

File: src/interactive-window/interactiveWindow.ts [hunk 7]
```diff
@@ -440,69 +366,62 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
...
-
     public dispose() {
         this.internalDisposables.forEach((d) => d.dispose());
         this.disconnectKernel();
     }
 
     @chainable()
-    public async addErrorMessage(
-        message: string,
-        getCell?: (editor: NotebookEditor) => NotebookCell | undefined
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:490]: No more callback hell

File: src/interactive-window/interactiveWindow.ts [hunk 8]
```diff
@@ -618,25 +553,31 @@ export class InteractiveWindow implements IInteractiveWindowLoadable {
         isDebug: boolean
     ) {
         traceInfoIfCI('InteractiveWindow.ts.createExecutionPromise.start');
-        // Wait for the cell to get created (required to insert error messages into cell output).
-        // When we wait for kernel to start, its possible it will fail, and
-        // higher up, we insert errors into the cell (but the cell needs to have been inserted).
+        // Kick of starting kernels early.
+        const kernelPromise = this.startKernel();
```
Comment (DonJayamanne) [inline src/interactive-window/interactiveWindow.ts:557]: This is what fixes #9444, when we run each cell we need to trigger the kernel start.
That's what prompted most of this refactor

File: src/kernels/helpers.ts [hunk 9]
```diff
@@ -1867,7 +1867,7 @@ function handleExecuteSilentErrors(
 async function switchController(
     resource: Resource,
     serviceContainer: IServiceContainer
-): Promise<VSCodeNotebookController | undefined> {
+): Promise<{ controller: NotebookController; metadata: KernelConnectionMetadata } | undefined> {
```
Comment (DonJayamanne) [inline src/kernels/helpers.ts:1870]: The object VSCodeNotebookController was too broad, we didn't need that whole object, all we need is the controller and the metadata.

File: src/test/datascience/notebook/helper.ts [hunk 10]
```diff
@@ -255,9 +260,11 @@ async function waitForKernelToChangeImpl(
 
     // Find the kernel id that matches the name we want
     let id: string | undefined;
-    const labelOrId = 'labelOrId' in criteria ? criteria.labelOrId : undefined;
+    let labelOrId = 'labelOrId' in criteria ? criteria.labelOrId : undefined;
     if (labelOrId) {
-        id = notebookControllers?.find((k) => (labelOrId && k.label === labelOrId) || (k.id && k.id == labelOrId))?.id;
+        id = notebookControllers
+            ?.filter((k) => (criteria.isInteractiveController ? k.id.includes(InteractiveControllerIdSuffix) : true))
```
Comment (DonJayamanne) [inline src/test/datascience/notebook/helper.ts:266]: I'm surprised our tests work today, 
Either they are not working correctly or we don't have tests that change kernels in IW.
Because the old code didn't work at all, we'd end up getting a controller that was dedicated for IPynb Notebooks.
This ensures we use the IW specific controller.

File: src/test/datascience/notebook/helper.ts [hunk 11]
```diff
@@ -846,10 +869,17 @@ export async function hijackPrompt(
             ('contains' in message && msg.trim().includes(message.contains.trim())) ||
             ('endsWith' in message && msg.endsWith(message.endsWith))
         ) {
+            messageDisplayed.push(msg);
             traceInfo(`Exact Message found '${msg}'`);
             displayCount += 1;
             displayed.resolve(true);
             if (buttonToClick) {
+                if (!buttonToClick.dismissPrompt && buttonToClick?.clickImmediately === true && buttonToClick.text) {
```
Comment (DonJayamanne) [inline src/test/datascience/notebook/helper.ts:877]: Tweeked this function so that we can use the same stub, but change what buttons are clicked.

File: src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts [hunk 12]
```diff
@@ -272,20 +292,201 @@ suite('DataScience Install IPyKernel (slow) (install)', function () {
...
 
-        const cell = notebookDocument.cellAt(0)!;
-        assert.equal(cell.outputs.length, 0);
+        // Hijack the select kernel functionality so it selects the correct kernel
+        const stub = sinon.stub(kernelSelector, 'selectKernel').callsFake(async function () {
+            // Now that we have selected a kernel, next time we get the prompt again, just dismiss the prompt.
+            promptOptions.dismissPrompt = true;
+            delete promptOptions.text;
+            // In tests, things hang as the IW isn't focused.
+            void activeInteractiveWindow.show(false);
```
Comment (DonJayamanne) [inline src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts:336]: This is a very very weird issue.
The tests fail locally because the IW is no longer the active editor.
Hence when we get the kernel selection code, it fails as that code checks whether there's an active notebook editor, and since its null, that method waits indefinitely for something to get active.

File: src/interactive-window/interactiveWindowProvider.ts [hunk 13]
```diff
@@ -120,40 +130,85 @@ export class InteractiveWindowProvider implements IInteractiveWindowProvider, IA
...
+            this.pendingCreations = this.pendingCreations.filter((item) => item !== creationInProgress.promise);
+        }
+    }
+    private async createEditor(
+        preferredController: VSCodeNotebookController | undefined,
+        resource: Resource,
+        mode: InteractiveWindowMode,
+        commandManager: ICommandManager
+    ): Promise<[Uri, NotebookEditor]> {
+        const controllerId = preferredController ? `${JVSC_EXTENSION_ID}/${preferredController.id}` : undefined;
```
Comment (rchiodo) [inline src/interactive-window/interactiveWindowProvider.ts:195]: If you didn't need this trace message you could do the creation of the editor at the same time as figuring out the preferred controller.

Comment (rchiodo) [reply src/interactive-window/interactiveWindowProvider.ts:195]: The calling function has to wait for the preferredController and its only usage is this trace message. The calling function could instead create the editor at the same time the preferred controller is coming up.

File: src/platform/errors/interactiveCellResultError.ts [hunk 14]
```diff
@@ -1,5 +1,11 @@
 // Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT License.
 
+import { NotebookCell } from 'vscode';
+
 // Small helper error to use in our class
-export class InteractiveCellResultError extends Error {}
+export class InteractiveCellResultError extends Error {
+    constructor(public readonly cell: NotebookCell) {
+        super('Cell failed to execute');
```
Comment (rchiodo) [inline src/platform/errors/interactiveCellResultError.ts:9]: Does this message need to be localized?

**Review by rchiodo — APPROVED** [review]
I presume we're going to wait till Sunday/Monday to submit this? Wait until Ian creates the release branch?

**Comment by DonJayamanne** [comment]
> till Sunday/Monday to submit this?

oh yes, as discussed no rush to put this into the release

File: src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts [hunk 15]
```diff
@@ -246,20 +254,32 @@ suite('DataScience Install IPyKernel (slow) (install)', function () {
...
-    test('Ensure ipykernel install prompt is displayed every time you try to run a cell in an Interactive Window', async function () {
+    test('Ensure ipykernel install prompt is displayed every time you try to run a cell in an Interactive Window and you can switch kernels', async function () {
         if (IS_REMOTE_NATIVE_TEST) {
             return this.skip();
         }
+        // This is a complex test that tests the following workflow (which used to fail)
+        // Verify errors are displayed against the cells being executed.
+        // 1. Run cell against env that does not have ipykernel
+        // 2. Ensure we get a prompt
+        // 3. Dismiss the prompt (at this point we'd get yet another prompt).
```
Comment (amunger) [inline src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts:265]: I like the outline of what the test is doing, but I don't think we need to add information about what was once broken.

File: src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts [hunk 16]
```diff
@@ -246,20 +254,32 @@ suite('DataScience Install IPyKernel (slow) (install)', function () {
...
+        // 4. Run another cell & we should get another prompt (this didn't work)
+        // 5. Run another cell & we should get another prompt (this didn't work)
+        // 6. Run another cell & select another kernel without ipykernel
+        // 7. We should get a prompt, however we used to get prompt for the previous env
```
Comment (amunger) [inline src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts:269]: 7/8. We should get two prompts: one for the original env, and one for the new one we switched to

File: src/interactive-window/interactiveWindowProvider.ts (hunk 13 above)
Comment (DonJayamanne) [reply src/interactive-window/interactiveWindowProvider.ts:195]: I moved the trace message above, however we do need the preferred controller before this step, as its used to create the IW a few lines further below.

File: src/platform/errors/interactiveCellResultError.ts (hunk 14 above)
Comment (DonJayamanne) [reply src/platform/errors/interactiveCellResultError.ts:9]: No need, this is not displayed to the user.

File: src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts (hunk 15 above)
Comment (DonJayamanne) [reply src/test/datascience/jupyter/kernels/installationPrompts.vscode.test.ts:265]: Leaving it there, so it never gets removed as being deemed unnecessary
