### PR TITLE
Do not add self to disposables

### LINKED ISSUE #15550: stack overflow on dispose
Seems to be a circular reference in this module, and disposing it causes quite a few errors

```
Dispose() failed for [object Object] RangeError: Maximum call stack size exceeded
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:106:28)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
```

possibly from https://github.com/microsoft/vscode-jupyter/commit/0a90f082189e72e9214c6ab9b4ed56d148deee3b

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
ispose() failed for [object Object] RangeError: Maximum call stack size exceeded
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:106:28)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23)
    at ImportTracker.dispose (c:\src\vscode-jupyter\src\standalone\import-export\importTracker.ts:105:9)
    at dispose (c:\src\vscode-jupyter\src\platform\common\utils\lifecycle.ts:43:23) {stack: 'RangeError: Maximum call stack size exceeded
…\platform\\common\\utils\\lifecycle.ts:43:23)', message: 'Maximum call stack size exceeded'}
```

</p>
</details>

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #15550

### CODE REVIEW

File: src/standalone/import-export/importTracker.ts [hunk 1]
```diff
@@ -93,11 +90,10 @@ export class ImportTracker implements IExtensionSyncActivationService, IDisposab
             this,
             disposables
```
Comment (karthiknadig) [inline src/standalone/import-export/importTracker.ts:91]: @DonJayamanne should it be `this.disposables`?

Comment (DonJayamanne) [reply src/standalone/import-export/importTracker.ts:91]: that shouldn't matter, &  it shouldn't cause a recursive
But needs to be changed to be consistent,
