### PR TITLE
Fix export interactive as jupyter notebook

### LINKED ISSUE #7947: Command `jupyter.exportoutputasnotebook` is no longer supported in Interactive window
We're throwing an error `no supported`.

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #7947

### CODE REVIEW

File: src/client/datascience/types.ts [hunk 1]
```diff
@@ -449,7 +449,6 @@ export interface IInteractiveWindow extends IInteractiveBase {
     ): Promise<boolean>;
     expandAllCells(): Promise<void>;
     collapseAllCells(): Promise<void>;
-    exportCells(): void;
```
Comment (DonJayamanne) [inline src/client/datascience/types.ts:452]: Yay....

**Review by DonJayamanne — APPROVED** [review]
