### PR TITLE
clear pw list as well as the server list on the clear servers command

### LINKED ISSUE #8956: "Clear Jupyter remote server list" doesn't clear related passwords
## Environment data

-   VS Code version: 1.64.0
-   Jupyter Extension version: 2022.1.1001775990
-   Python Extension version: 2022.0.1786462952
-   OS and version: Arch Linux 5.16.5-arch1-1
-   Python and/or Anaconda version: Python 3.10.2 and conda 4.10.3
-   Type of virtual environment used: conda
-   Jupyter server running: Remote in Kubeflow (JupyterLab 2.2.9 on Kubeflow 1.2)

## Expected behaviour

1. Execute `Jupyter: Clear Jupyter remote server list`.
2. Remote server list and authentication details are cleared.
3. Adding a new remote connection `Jupyter: Specify local or remote server for connection...`  --> `Existing` asks for URL **and** password.

## Actual behaviour

1. Execute `Jupyter: Clear Jupyter remote server list`.
2. Remote server list is cleared.
3. Adding a new remote connection`Jupyter: Specify local or remote server for connection...`  --> `Existing` asks for URL but reuses the password before deletion.

## Steps to reproduce:

_Assuming you're using a Kubeflow remote notebook server_

1. Get the Url of the remote notebook, e.g.: `http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test/`.
2. Get the value of the `authservice_session` cookie for authentication.
3. Add Url and cookie value as password as an existing remote server using `Jupyter: Specify local or remote server for connection...`  --> `Existing`.
4. Verify that the connection could be established.
5. Execute `Jupyter: Clear Jupyter remote server list`.
6. Try adding Url and cookie value as password as an existing remote server using `Jupyter: Specify local or remote server for connection...`  --> `Existing` again
7. Password prompt won't come and logs show that "old" password was used.

I tried to figure out on my own where those credentials/mappings are stored by checking the source code, but ended up with `encryptedStorage` and other stuff I couldn't handle on my own right away.
If there is a way to clean this up locally as a workaround, please tell me.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

After initial adding the remote server:
```
Info 12:08:14: Checking for server existence.
Info 12:08:14: Checking for server usability.
Info 12:08:14: Starting notebook server.
Info 12:08:14: Connecting to server
Info 12:08:14: Connecting to process server
Info 12:08:14: Connecting server kernel http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/
Connecting to Jupyter server at http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/
Info 12:08:31: Creating server with settings : {"baseUrl":"http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","appUrl":"","wsUrl":"ws://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511; authservice_session=MTY0NDMxMjc4MXxOd3dBTkRJM1dFdFlWRFpGV0ZKTVZFWlZVakpWV2xjMlVrZENWMVpQVjB4S1dGSmFVVWt6V1ZGRVdFWTJWMW8zVUVOQlRrMHpUVkU9fBWLb-3eQLTfQ5WVga75HWuexPjr_0qlcxZKRrH0Iq9a","X-XSRFToken":"2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511"}}}
Info 12:08:31: Connection complete server
Info 12:08:31: Server started.
Info 12:08:31: Creating server with settings : {"baseUrl":"http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","appUrl":"","wsUrl":"ws://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511; authservice_session=MTY0NDMxMjc4MXxOd3dBTkRJM1dFdFlWRFpGV0ZKTVZFWlZVakpWV2xjMlVrZENWMVpQVjB4S1dGSmFVVWt6V1ZGRVdFWTJWMW8zVUVOQlRrMHpUVkU9fBWLb-3eQLTfQ5WVga75HWuexPjr_0qlcxZKRrH0Iq9a","X-XSRFToken":"2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511"}}}
Info 12:08:31: Disposing session manager
Info 12:08:31: SessionManager - dispose contents manager
Info 12:08:31: ShutdownSessionAndConnection - dispose session manager
Info 12:08:31: Finished disposing jupyter session manager
```

After removal and 2nd adding of the remote server:
```
Info 12:10:55: Checking for server existence.
Info 12:10:55: Checking for server usability.
Info 12:10:55: Starting notebook server.
Info 12:10:55: Server started.
Info 12:10:55: Creating server with settings : {"baseUrl":"http://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","appUrl":"","wsUrl":"ws://kubeflow.someproject.somecompany.com/notebook/shared/vs-code-test2/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511; authservice_session=MTY0NDMxMjc4MXxOd3dBTkRJM1dFdFlWRFpGV0ZKTVZFWlZVakpWV2xjMlVrZENWMVpQVjB4S1dGSmFVVWt6V1ZGRVdFWTJWMW8zVUVOQlRrMHpUVkU9fBWLb-3eQLTfQ5WVga75HWuexPjr_0qlcxZKRrH0Iq9a","X-XSRFToken":"2|b3c62365|b6494dfe95fedae7b0b96958cecc88dc|1644318511"}}}
Info 12:10:55: Disposing session manager
Info 12:10:55: SessionManager - dispose contents manager
Info 12:10:55: ShutdownSessionAndConnection - dispose session manager
Info 12:10:55: Finished disposing jupyter session manager
```

</p>
</details>

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #8956

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]

File: src/kernels/jupyter/commands/serverSelector.ts [hunk 1]
```diff
@@ -64,6 +65,10 @@ export class JupyterServerSelectorCommand implements IDisposable {
     }
 
     private async clearJupyterUris(): Promise<void> {
+        // Clear out our saved passwords from this session as well
```
Comment (rebornix) [inline src/kernels/jupyter/commands/serverSelector.ts:68]: @IanMatthewHuff not directly related to this PR: do we clear jupyter uri when removing a server from the server quick pick? It seems we should have a `clearJupyterUri(uri: string)` to clear the password connection info for a url and call that when users manually remove a url from the server list.

Comment (IanMatthewHuff) [reply src/kernels/jupyter/commands/serverSelector.ts:68]: @rebornix That's a good catch. I totally forgot that options. Follow up PR today.
