### PR TITLE
Fixes to IPyWidgets not loading script soruces

### LINKED ISSUE #9720: Matplot lib & other widgets are broken in main branch
The following no longer works
```
%matplotlib widget
from ipywidgets import interactive
import matplotlib.pyplot as plt
import numpy as np

def f(m, b):
    plt.figure(2)
    x = np.linspace(-10, 10, num=1000)
    plt.plot(x, m * x + b)
    plt.ylim(-5, 5)
    plt.show()

interactive_plot = interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
output = interactive_plot.children[-1]
output.layout.height = '350px'
interactive_plot
```

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9720

Will be adding tests for these widgets today/tomorrow.
Ran into this while writing up some tests.

### CODE REVIEW

File: src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export class IPyWidgetScriptSource {
         uriConverter.requestUri(
             (e) =>
                 this.postEmitter.fire({
-                    message: InteractiveWindowMessages.ConvertUriForUseInWebViewResponse,
+                    message: InteractiveWindowMessages.ConvertUriForUseInWebViewRequest,
```
Comment (rchiodo) [inline src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts:58]: Wooops. Sorry.

Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts:58]: Possibly changed inadvertently as part of the web refactor.
This resulted in the Uri never getting resolved (basically a promise was never resolved & on the webview side the script was never made available)

**Review by rchiodo — APPROVED** [review]

File: src/webviews/webview-side/ipywidgets/common/scriptManager.ts [hunk 2]
```diff
@@ -130,7 +130,9 @@ export class ScriptManager extends EventEmitter {
                         moduleVersion,
                         new Error(`Timeout getting source for ${moduleName}:${moduleVersion}`),
                         true
-                    ).ignoreErrors();
+                    ).catch(() => {
```
Comment (DonJayamanne) [inline src/webviews/webview-side/ipywidgets/common/scriptManager.ts:133]: During dev this fails, as we aren't importing the file that contains the necessary extensions.

File: src/webviews/webview-side/ipywidgets/common/scriptManager.ts [hunk 3]
```diff
@@ -199,6 +201,7 @@ export class ScriptManager extends EventEmitter {
         // Now resolve promises (anything that was waiting for modules to get registered can carry on).
         sources.forEach((source) => {
             this.registeredWidgetSources.set(source.moduleName, source);
+            this.widgetsRegisteredInRequireJs.add(source.moduleName);
```
Comment (DonJayamanne) [inline src/webviews/webview-side/ipywidgets/common/scriptManager.ts:204]: Not sure how this went missing, but this was also required. Even if this wasn't added, then we'd re-download the js file and try all over again, this is meant to avoid that.
