### PR TITLE
Fix ipywidget comms

### LINKED ISSUE #9714: IPyWidgets is broken in VS Code insiders

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9714

### CODE REVIEW

File: src/kernels/ipywidgets-message-coordination/notebookIPyWidgetCoordinator.ts [hunk 1]
```diff
@@ -104,14 +105,16 @@ export class NotebookIPyWidgetCoordinator {
...
         @inject(IServiceContainer) private readonly serviceContainer: IServiceContainer,
-        @inject(IDisposableRegistry) disposableRegistry: IDisposableRegistry,
+        @inject(IDisposableRegistry) private readonly disposableRegistry: IDisposableRegistry,
         @inject(IAsyncDisposableRegistry) private readonly asyncDisposableRegistry: IAsyncDisposableRegistry,
         @inject(IVSCodeNotebook) private readonly notebook: IVSCodeNotebook,
         @inject(INotebookControllerManager) private readonly controllerManager: INotebookControllerManager
     ) {
-        notebook.onDidChangeVisibleNotebookEditors(this.onDidChangeVisibleNotebookEditors, this, disposableRegistry);
-        notebook.onDidCloseNotebookDocument(this.onDidCloseNotebookDocument, this, disposableRegistry);
-        controllerManager.onNotebookControllerSelected(this.onDidSelectController, this, disposableRegistry);
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/notebookIPyWidgetCoordinator.ts:114]: Code was in the ctor and when we got this instance from test code, this class would get instantiated and things work.
Moved into an activate function to be more specific instead of relying on side effects of ctor

**Review by rchiodo — APPROVED** [review]

**Review by amunger — APPROVED** [review]
