### PR TITLE
Fixes related to loading widget scripts

### LINKED ISSUE #10434: Clean up support for ipywidgets in remote jupyter scenarios
Problems:
* Custom ipywidgets do not work in vscode.web (we don't download the JS files) [#10060](https://github.com/microsoft/vscode-jupyter/issues/10060)
* Custom widgets that have additional static resources do not get downloaded (applies to web, desktop & remove jupyter) [#8834](https://github.com/microsoft/vscode-jupyter/issues/8834)
* JS files for custom widgets are not loaded correctly (applies to web, desktop & remote) [#10319](https://github.com/microsoft/vscode-jupyter/issues/10319)
* If there's no network connection (to download widget js files from CDN) then custom ipywidgets do not work
	* Because of the previous 3 issues

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #10434, #10060, #8834

### CODE REVIEW

File: src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+import { IWidgetScriptSourceProvider, WidgetScriptSource } from './types';
+
+// Source borrowed from https://github.com/jupyter-widgets/ipywidgets/blob/54941b7a4b54036d089652d91b39f937bde6b6cd/packages/html-manager/src/libembed-amd.ts#L33
+const unpgkUrl = 'https://unpkg.com/';
+const jsdelivrUrl = 'https://cdn.jsdelivr.net/npm/';
+
+const GlobalStateKeyToTrackIfUserConfiguredCDNAtLeastOnce = 'IPYWidgetCDNConfigured';
+const GlobalStateKeyToNeverWarnAboutScriptsNotFoundOnCDN = 'IPYWidgetNotFoundOnCDN';
+
+function moduleNameToCDNUrl(cdn: string, moduleName: string, moduleVersion: string) {
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts:29]: We don't need two seprate clases now.
When dealing with CDN, we cannot save the CDN file to disk, that breaks widgets.
If user doesn't have access to the internet we'll display  a warning message indicating the fact that cdn isn't being used due to lack of connectivity.

File: src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts [hunk 2]
```diff
@@ -0,0 +1,260 @@
...
+            traceVerbose(`Failed downloading ${moduleName}:${moduleVersion} from ${cdn}`);
+            return undefined;
+        }
+    }
+    private warnIfNoAccessToInternetFromWebView() {
+        //
+    }
+
+    private async configureWidgets(): Promise<void> {
+        if (this.configuredScriptSources.length !== 0) {
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts:175]: Moved code related to displaying messages for CDN into the CDN class, instaead of having that elsewhere.

File: src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts [hunk 3]
```diff
@@ -87,35 +85,28 @@ export class IPyWidgetScriptSource {
...
+                            payload: baseUrl.toString()
+                        });
+                    }
+                })
+                .catch((ex) => {
+                    console.error(`Failed to get baseUrl`, ex);
+                });
+        } else if (message === IPyWidgetMessages.IPyWidgets_IsOnline) {
+            const isOnline = (payload as { isOnline: boolean }).isOnline;
+            this.isWebViewOnline.resolve(isOnline);
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts:104]: Helps us determine from exension host whether the webview has access to the internet (i.e. whether we can access CDN resources from webview)

File: src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts [hunk 4]
```diff
@@ -127,7 +118,7 @@ export class IPyWidgetScriptSource {
         }
 
         if (!this.kernel) {
-            this.kernel = await this.kernelProvider.get(this.document.uri);
+            this.kernel = this.kernelProvider.get(this.document.uri);
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.ts:121]: unnecessary await

File: src/test/datascience/ipywidgets/samples/beakerx/LICENSE [hunk 5]
```diff
@@ -0,0 +1,201 @@
+Apache License
```
Comment (DonJayamanne) [inline src/test/datascience/ipywidgets/samples/beakerx/LICENSE:1]: I wanted to use the actual extension.js files for tests instead of crafting our own content.
Included the license files along with the extesnsion.js files.

File: src/kernels/common/baseJupyterSession.ts [hunk 6]
```diff
@@ -379,7 +379,9 @@ export abstract class BaseJupyterSession implements IJupyterSession {
                             const jupyterLabSerialize =
                                 require('@jupyterlab/services/lib/kernel/serialize') as typeof import('@jupyterlab/services/lib/kernel/serialize'); // NOSONAR
                             const message =
-                                typeof msg.msg === 'string' ? jupyterLabSerialize.deserialize(msg.msg) : msg.msg;
+                                typeof msg.msg === 'string' || msg.msg instanceof ArrayBuffer
```
Comment (DonJayamanne) [inline src/kernels/common/baseJupyterSession.ts:382]: Bug i found while testing, we weren't deserializing buffers

File: src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts [hunk 7]
```diff
@@ -0,0 +1,294 @@
...
+        default:
+            break;
+    }
+}
+/**
+ * Widget scripts are found in CDN.
+ * Given an widget module name & version, this will attempt to find the Url on a CDN.
+ * We'll need to stick to the order of preference prescribed by the user.
+ */
+export class CDNWidgetScriptSourceProvider implements IWidgetScriptSourceProvider {
```
Comment (DonJayamanne) [inline src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts:70]: Merged the web and node files into one, we don't need to download the cdn files into the local file system anymore.
If we do that then things will not work, e.g. ipyvolume and a few other widgets don't work with that approach.

If user doesn't have access to the internet from the webview, then we'll not use CDN, this way we're consistent. I.e. we always use CDN when there's network connection, else fallback.
If here's no network access we're now displaying a warning message.

File: src/platform/common/platform/fileSystem.node.ts [hunk 8]
```diff
@@ -90,28 +89,28 @@ export class FileSystem extends FileSystemBase implements IFileSystemNode {
...
+        options: { overwrite: boolean } = { overwrite: true }
+    ): Promise<void> {
+        await fs.copy(source, destination, { overwrite: options?.overwrite });
     }
 
     async readLocalData(filename: string): Promise<Buffer> {
-        const uri = vscode.Uri.file(filename);
-        const data = await this.vscfs.readFile(uri);
-        return Buffer.from(data);
+        return fs.readFile(filename);
```
Comment (DonJayamanne) [inline src/platform/common/platform/fileSystem.node.ts:104]: Using VSC API here is totally unnecessary its very slow. 
Since these are local only (the methods are `local` , hence easier & more efficient to just use native node modules.

File: news/2 Fixes/10060.md [hunk 9]
```diff
@@ -0,0 +1 @@
+Ensure IPyWidgets get loaded correctly when loading resources from the CDN, Remote Jupyter or local the Python Environment.
```
Comment (DonJayamanne) [inline news/2 Fixes/10060.md:1]: Still requires some more testing, but this is ready for review.
Will look into adding more tests or at least re-enabling some of the widget tests tomorrow.

File: src/test/datascience/ipywidgets/samples/beakerx/LICENSE (hunk 5 above)
Comment (IanMatthewHuff) [reply src/test/datascience/ipywidgets/samples/beakerx/LICENSE:1]: Wondering if some automated check tool is going to flag us for having a different license in the repo. But I guess we'll see if anything like that crops up moving forward.

File: src/interactive-window/debugger/jupyter/kernelDebugAdapter.ts [hunk 10]
```diff
@@ -84,9 +84,6 @@ export class KernelDebugAdapter extends KernelDebugAdapterBase {
             const response = await this.session.customRequest('dumpCell', { code });
 
             // We know jupyter will strip out leading white spaces, hence take that into account.
-            const lines = metadata.generatedCode!.realCode.splitLines({ trim: false, removeEmptyEntries: false });
```
Comment (rchiodo) [inline src/interactive-window/debugger/jupyter/kernelDebugAdapter.ts:87]: Unused code?

File: src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts (hunk 1 above)
Comment (rchiodo) [reply src/kernels/ipywidgets-message-coordination/cdnWidgetScriptSourceProvider.ts:26]: This could be a rename instead of an add? Then we wouldn't lose history.

File: src/kernels/ipywidgets-message-coordination/localIPyWidgetScriptManager.node.ts [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+        let overwrite = this.overwriteExistingFiles;
+
+        try {
+            const stopWatch = new StopWatch();
+            this.sourceNbExtensionsPath = await this.nbExtensionsPathProvider.getNbExtensionsParentPath(this.kernel);
+            if (!this.sourceNbExtensionsPath) {
+                return;
+            }
+            const kernelHash = getTelemetrySafeHashedString(this.kernel.kernelConnectionMetadata.id);
+            const baseUrl = Uri.joinPath(this.context.extensionUri, 'tmp', 'scripts', kernelHash, 'jupyter');
```
Comment (rchiodo) [inline src/kernels/ipywidgets-message-coordination/localIPyWidgetScriptManager.node.ts:48]: Not sure where to put the comment but it might make sense to say why we need to copy the file. It's because we can't load from disk in the webview. We need a toWebviewUri possible location.

**Review by rchiodo — APPROVED** [review]
Awesome job. Looks like we're going to have ALL widgets working now.

File: src/kernels/ipywidgets-message-coordination/remoteIPyWidgetScriptManager.ts [hunk 12]
```diff
@@ -0,0 +1,108 @@
...
+        if (outputs.length === 0) {
+            return [];
+        }
+        const output = outputs[0] as nbformat.IStream;
+        if (output.output_type !== 'stream' || output.name !== 'stdout') {
+            return [];
+        }
+        try {
+            // Value will be an array of the form `['xyz', 'abc']`
+            const items = (output.text as string)
```
Comment (IanMatthewHuff) [inline src/kernels/ipywidgets-message-coordination/remoteIPyWidgetScriptManager.ts:82]: Language conversions like this always feel a bit scary. Like I think that , is a valid file path character on linux. I think since you have the logging in the catch case this should be ok.

**Review by IanMatthewHuff — APPROVED** [review]

**Comment by amunger** [comment]
empty news file

File: src/interactive-window/debugger/jupyter/kernelDebugAdapter.ts (hunk 10 above)
Comment (DonJayamanne) [reply src/interactive-window/debugger/jupyter/kernelDebugAdapter.ts:87]: Yes.

File: src/kernels/ipywidgets-message-coordination/localIPyWidgetScriptManager.node.ts (hunk 11 above)
Comment (DonJayamanne) [reply src/kernels/ipywidgets-message-coordination/localIPyWidgetScriptManager.node.ts:48]: I'll put the comment at the class level

File: src/kernels/ipywidgets-message-coordination/nbExtensionsPathProvider.web.ts [hunk 13]
```diff
@@ -0,0 +1,23 @@
...
+import { IKernel } from '../types';
+import { INbExtensionsPathProvider } from './types';
+
+@injectable()
+export class NbExtensionsPathProvider implements INbExtensionsPathProvider {
+    getNbExtensionsParentPath(kernel: IKernel): Uri | undefined {
+        switch (kernel.kernelConnectionMetadata.kind) {
+            case 'connectToLiveRemoteKernel':
+            case 'startUsingRemoteKernelSpec': {
+                return Uri.parse(kernel.kernelConnectionMetadata.baseUrl);
```
[the remark this answers is not in the document]
Comment (DonJayamanne) [reply src/kernels/ipywidgets-message-coordination/nbExtensionsPathProvider.web.ts:15]: I think it should work, because their url is basically a proxy, hence requests shoudl still flow through.
If not, then there's really nothing much we can do.
I think with Jupyter Hub it will work as jupyter hub is basically just launching a classic Jupyter notbeook application, just as though we launched them manually.

File: src/kernels/ipywidgets-message-coordination/remoteIPyWidgetScriptManager.ts (hunk 12 above)
Comment (DonJayamanne) [reply src/kernels/ipywidgets-message-coordination/remoteIPyWidgetScriptManager.ts:82]: Doesn't work as expected, not going to spend more time on that.
