### PR TITLE
Fixes for launching non-Python kernels

### LINKED ISSUE #11519: Unable to detect nor run R kernels
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Extension versions until 2022.6.XXX detect R kernels correctly but 2022.7.XXX and later versions do not detect R kernels. 

[This](https://github.com/FredHutch/tfcb_2022/blob/02bcda9934de94c60850ffb266f45088d210a955/.devcontainer/Dockerfile#L17-L32) is the definition of the Jupyter R environment and [this](https://github.com/FredHutch/tfcb_2022/blob/02bcda9934de94c60850ffb266f45088d210a955/.devcontainer/devcontainer.json) is the devcontainer.json file loading the extension.

Jupyter output log: 
[show_jupyter_output.log](https://github.com/microsoft/vscode-jupyter/files/9700895/show_jupyter_output.log)

See screencast gifs below for kernel picking in different extension versions:

v2022.6.120

[kernel_00002.webm](https://user-images.githubusercontent.com/1737087/193677801-7b43a53e-dafc-4702-9741-8327228acfeb.webm)

v2022.08.100 (latest version)

[kernel_00001.webm](https://user-images.githubusercontent.com/1737087/193677711-fe25cb34-1481-4782-bd68-ef2a11badeaa.webm)

### VS Code Version

1.71.0

### Jupyter Extension Version

2022.8.1002431955

### Jupyter logs

_No response_

### Coding Language and Runtime Version

R

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

N/A or Not sure

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #11519

### CODE REVIEW

**Comment by yilmazdurmaz** [comment]
I have tried your 2023.2.100 build with both R and Julia kernels, and using 3 conda environments.

`Sys.getenv(c("CONDA_PREFIX"))` with the R kernels, and `ENV["CONDA_PREFIX"]` for Julia kernels (used inside notebook cells) are showing correct paths for all 3 environments.

conda forge does not have a compilation for Windows. As I am on Windows, I had to install it to a single location and I had to trick Julia kernels being under different conda environments by copying the user kernel folder under the kernel folders of those environments. This might need another peek from Linux and Mac, but I will still call it a win-win as R kernels worked without a problem.

Thanks for having the time for the fix.

File: src/platform/common/application/applicationShell.ts [hunk 1]
```diff
@@ -80,6 +81,7 @@ export class ApplicationShell implements IApplicationShell {
         ...items: T[]
     ): Thenable<T>;
     public showErrorMessage(message: any, options?: any, ...items: any[]) {
+        traceInfoIfCI(`Show Error Message ${message}, ${JSON.stringify(items)}`);
```
Comment (DonJayamanne) [inline src/platform/common/application/applicationShell.ts:84]: Came across a flaky test where a dialog message appeared on CI, this is to see what was the last message that was displayed & caused tests to fail

**Review by bpasero — APPROVED** [review]
