### PR TITLE
detilde traceback file path

### LINKED ISSUE #9058: jupyter extension does not understand "~" refer to home directory
I was referred to post the issue here from microsoft/vscode#143252

## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version (available under the Extensions sidebar):  v2022.1.1301854968 
-   Python Extension version (available under the Extensions sidebar): v2022.0.1814523869 
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H2 x64
-   Python and/or Anaconda version: Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

Open file without no issue by treating `~` as user directory

## Actual behaviour

Cannot open file because treating `~` literally as `~`

## Steps to reproduce:

1. Run some python codes that will raise error
2. Attempt to open one of the file in trace (e.g. click on the number `267` below to open `constant_op.py` ). Since VSCode seems to treat `~` literally `~`, it will fail to open the file. If select "create file", a folder `~` will literally be created under C drive.

image

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #9058

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/client/datascience/editor-integration/cellhashprovider.ts [hunk 1]
```diff
@@ -535,7 +537,9 @@ export class CellHashProvider implements ICellHashProvider {
 
         const fileMatch = /^File.*?\[\d;32m(.*):\d+.*\u001b.*\n/.exec(traceFrame);
         if (fileMatch && fileMatch.length > 1) {
-            const fileUri = Uri.file(fileMatch[1]);
+            // We need to untilde the file path here for the link to work in VS Code
```
Comment (IanMatthewHuff) [inline src/client/datascience/editor-integration/cellhashprovider.ts:540]: Wasn't in the milestone, but by the time I investigate this customer bug it was basically a one line fix, so checked in it.

**Review by rchiodo — APPROVED** [review]
