### PR TITLE
Ensure we support localizations in error renderer

### LINKED ISSUE #12595: Not seeing errors
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After updating my VS Insiders version I am no longer seeing notebook error tracebacks. I've disabled all extensions besides Jupyter and Python. I just see a circled X with no output.

Screenshot:
image

### VS Code Version

Version: 1.75.0-insider (Universal) Commit: 9ccc2b3b30c122afe45bc6722bef0e3901fb2806

### Jupyter Extension Version

v2023.1.2000202160

### Jupyter logs

No text in output panel. 

### Coding Language and Runtime Version

Python v3.9.6

### Language Extension Version (if applicable)

Python v2023.1.10181031

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Occurs when running either local or remote

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #12595

### CODE REVIEW

File: src/webviews/webview-side/error-renderer/index.ts [hunk 1]
```diff
@@ -162,48 +164,27 @@ export function truncatedArrayOfString(
...
 export const activate: ActivationFunction = (context) => {
     const latestContext = context as RendererContext<void> & { readonly settings: { readonly lineLimit: number } };
-    let loadLocalization: Promise<void>;
-    let isReady = false;
+    const loadLocalization = createDeferred();
 
     if (context.postMessage && context.onDidReceiveMessage) {
-        const requestLocalization = () => {
-            context.postMessage!({
-                type: 2 /** MessageType.LoadLoc */
```
Comment (DonJayamanne) [inline src/webviews/webview-side/error-renderer/index.ts:171]: This was the problem, we weren't using the constants but just the number.

File: src/webviews/webview-side/error-renderer/index.ts [hunk 2]
```diff
@@ -162,48 +164,27 @@ export function truncatedArrayOfString(
...
-                case 2:
-                    // load localization
-                    Localizations = {
-                        ...Localizations,
-                        ...e.data
-                    };
-                    isReady = true;
-                    _loadLocResolveFunc();
-                    break;
+            if (e.type === ErrorRendererMessageType.ResponseLoadLoc) {
```
Comment (DonJayamanne) [inline src/webviews/webview-side/error-renderer/index.ts:175]: Now using the right enums

File: src/webviews/extension-side/error-renderer/index.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+export class ExtensionSideRenderer implements IDisposable, IExtensionSyncActivationService {
+    private disposables: IDisposable[] = [];
+    constructor(@inject(IDisposableRegistry) disposables: IDisposableRegistry) {
+        disposables.push(this);
+    }
+    activate(): void {
+        const errorRendererMessage = vscode.notebooks.createRendererMessaging('jupyter-error-renderer');
+        const loadLocMessage = {
+            type: ErrorRendererMessageType.ResponseLoadLoc,
+            payload: {
```
Comment (DonJayamanne) [inline src/webviews/extension-side/error-renderer/index.ts:26]: Only passing the necessary localized strings

**Review by rebornix — APPROVED** [review]
