### PR TITLE
Ensure we use the real "print" when checking for ipykernel

### LINKED ISSUE #11546: Jupyter Cell debugging does not work with rich (override of print())
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Ran into bogus "ipykernel setup required" message in large jupyter notebook and after much venv debugging realized it was a bug with [rich](https://rich.readthedocs.io/) a popular Python library for terminal text.

A minimal example is to import print from rich, then try to debug a notebook cell. The capture below shows the scenario. 

test2

Steps:
- setup rich with `pip install rich`
- create a notebook with a single cell containing
```python
from rich import print
```
- save the notebook
- select debug cell from the cell dropdown once - *it will work* and execute the cell
- select debug cell **again** - *it will **NOT** work* and show `Ipykernel setup required for this feature`

### VS Code Version

Version: 1.71.2 Commit: 74b1f979648cc44d385a2286793c226e611f59e7 Date: 2022-09-14T21:07:15.900Z Electron: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 21.5.0 Sandboxed: No

### Jupyter Extension Version

Jupyter  v2022.8.1002431955 

### Jupyter logs

```shell
Visual Studio Code (1.71.2, undefined, desktop)
Jupyter Extension Version: 2022.8.1002431955.
Python Extension Version: 2022.14.0.
No workspace folder opened.
error 16:33:2.64: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.12
    loaded from: /Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/zeromq

	at load.path (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
	at p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62866)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
	at p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62866)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:503599)
	at __webpack_require__ (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:1383216)
	at l.zmqSupported (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2360645)
	at l.isSupportedForLocalLaunch (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2360388)
	at get isSupported [as isSupported] (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2360298)
	at t.registerTypes (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2376353)
	at /Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1792972
	at /Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1793727
	at /Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1793735
	at t.activate (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:1793857)
	at Tn._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17649)
	at Tn._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17307)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:15118
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
	at async E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 16:33:2.290: LSP Notebooks experiment is enabled
info 16:33:2.457: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 16:33:2.470: Preferred Remote kernel for /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb is undefined
info 16:33:2.470: Find preferred kernel for /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.14 ('amazonAGI-XQmsfcBC')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.14"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99"}}} & preferred interpreter /Users/bcs/.pyenv/versions/3.8.10/bin/python
info 16:33:2.476: Preferred Remote kernel for /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb is undefined
info 16:33:2.476: Preferred kernel .jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 16:33:2.477: PreferredConnection: .jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python.-m#ipykernel_launcher found for NotebookDocument: /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:33:2.518: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import jupyter"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import jupyter"
info 16:33:2.518: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import notebook"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import notebook"
info 16:33:2.518: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m pip list
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m pip list
info 16:33:2.592: Process Execution: > ~/.pyenv/versions/3.8.10/bin/python -m pip list
> ~/.pyenv/versions/3.8.10/bin/python -m pip list
info 16:33:2.616: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m jupyter kernelspec --version
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m jupyter kernelspec --version
info 16:33:2.882: Preferred Remote kernel for /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb is undefined
info 16:33:32.158: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python.-m#ipykernel_launcher' (Python Path: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC, EnvType: PipEnv, EnvName: 'amazonAGI-XQmsfcBC', Version: 3.9.14) for '/Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb' (disableUI=true)
info 16:33:32.158: Checking for server existence.
info 16:33:32.159: Checking for server usability.
info 16:33:32.176: Starting notebook server.
info 16:33:32.176: Connecting to server
info 16:33:32.176: Launching server
info 16:33:32.177: Starting Notebook
info 16:33:32.178: Generating custom default config at /var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/c78dc6da-5111-4e87-83d7-65d85c6cc387/jupyter_notebook_config.py
info 16:33:32.178: Starting Jupyter Notebook
Starting Jupyter from ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python
info 16:33:32.181: Creating daemon pool for /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python with env variables count 68
info 16:33:32.182: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
info 16:33:32.184: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
info 16:33:32.184: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 45602
info 16:33:32.226: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/bcs/work/experimental/amazonAGI/tuning/whisper" --config=/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/c78dc6da-5111-4e87-83d7-65d85c6cc387/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/bcs/work/experimental/amazonAGI/tuning/whisper" --config=/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/c78dc6da-5111-4e87-83d7-65d85c6cc387/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 16:33:32.226: Waiting for Jupyter Notebook
/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
info 16:33:32.431: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(

[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
info 16:33:32.543: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.

[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
info 16:33:32.543: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.

[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
info 16:33:32.544: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.

[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
info 16:33:32.545: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.

[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
info 16:33:32.546: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.

[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
info 16:33:32.546: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper

[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:
info 16:33:32.546: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:

[I 16:33:32.546 NotebookApp] http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
info 16:33:32.546: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 16:33:32.546 NotebookApp] http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c

info 16:33:32.548: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:33:32.546 NotebookApp]  or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
info 16:33:32.548: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 16:33:32.546 NotebookApp] http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
[I 16:33:32.546 NotebookApp]  or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c

info 16:33:32.549: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:33:32.546 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 16:33:32.550: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 16:33:32.546 NotebookApp] http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
[I 16:33:32.546 NotebookApp]  or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
[I 16:33:32.546 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

[C 16:33:32.549 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/bcs/Library/Jupyter/runtime/nbserver-45752-open.html
    Or copy and paste one of these URLs:
        http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
     or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
info 16:33:32.552: /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/bcs/work/experimental/amazonAGI/tuning/whisper' instead of '"/Users/bcs/work/experimental/amazonAGI/tuning/whisper"' if you require traitlets >=5.
  warn(
[I 16:33:32.543 NotebookApp] The port 8888 is already in use, trying another port.
[I 16:33:32.543 NotebookApp] The port 8889 is already in use, trying another port.
[I 16:33:32.544 NotebookApp] The port 8890 is already in use, trying another port.
[I 16:33:32.545 NotebookApp] The port 8891 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] The port 8892 is already in use, trying another port.
[I 16:33:32.546 NotebookApp] Serving notebooks from local directory: /Users/bcs/work/experimental/amazonAGI/tuning/whisper
[I 16:33:32.546 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 16:33:32.546 NotebookApp] http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
[I 16:33:32.546 NotebookApp]  or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
[I 16:33:32.546 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:33:32.549 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/bcs/Library/Jupyter/runtime/nbserver-45752-open.html
    Or copy and paste one of these URLs:
        http://localhost:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c
     or http://127.0.0.1:8941/?token=e791b3e12c9e3ac53492ba89fe3d6b7dbaa6ad62f9b7ef7c

info 16:33:32.735: Connecting to process server
info 16:33:32.735: Connecting server kernel http://localhost:8941/
info 16:33:32.735: Creating server with url : http://localhost:8941/
info 16:33:32.741: Connection complete server
info 16:33:32.742: Server started.
info 16:33:32.754: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:33:32.799 NotebookApp] Creating new notebook in 
info 16:33:32.806: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 16:33:32.825: installMissingDependencies /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python, ui.disabled=true for resource '/Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb'
info 16:33:32.827: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
info 16:33:32.911: Spec argv[0] updated from '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python' to '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python'
[I 16:33:32.951 NotebookApp] Kernel started: 95bce6e4-e6b0-472f-a846-6c62abde5f0e, name: python3914jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99
info 16:33:32.959: Waiting for idle on (kernel): 95bce6e4-e6b0-472f-a846-6c62abde5f0e -> unknown
[W 16:33:32.963 NotebookApp] delete /test-jvsc-f0726e77-8840-4d33-a622-06f34ba57f36fd24d9b0-9437-4f21-96d2-5dbbbf3277e4.ipynb
warn 16:33:33.42: Falling back to Python Execution Service due to failure in daemon g [Error]: Failed to execute using the daemon, Traceback (most recent call last):
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py", line 19, in <module>
    for si in server_list:
  File "/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/lib/python3.9/site-packages/notebook/notebookapp.py", line 2412, in list_running_servers
    with open(os.path.join(runtime_dir, file_name), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bcs/Library/Jupyter/runtime/nbserver-42682.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 135, in m_exec_file
    return self._execute_and_capture_output(exec_file)
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 106, in _execute_and_capture_output
    func()
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 132, in exec_file
    runpy.run_path(file_name, globals())
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py", line 46, in <module>
    builtins.print.write(result.stdout.decode(encoding))
AttributeError: 'builtin_function_or_method' object has no attribute 'write'

    at s.processResponse (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:7:37076)
    at s.execFileWithDaemon (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:7:37423)
    at s.exec (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:7:34468)
    at d.wrapCall (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:7:79841)
    at I.getRunningJupyterServers (/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2111755) {
  category: 'daemon'
}
info 16:33:33.44: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 16:33:33.274: Finished waiting for idle on (kernel): 95bce6e4-e6b0-472f-a846-6c62abde5f0e -> idle
info 16:33:33.274: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python.-m#ipykernel_launcher
info 16:33:33.275: Finished connecting kernel startUsingPythonInterpreter:.jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python./Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/python.-m#ipykernel_launcher
info 16:33:33.276: UpdateWorkingDirectoryAndPath in Kernel
info 16:33:33.277: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not
info 16:33:33.351: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not with 1 output(s)
info 16:33:33.351: Waiting for idle on (kernel): 95bce6e4-e6b0-472f-a846-6c62abde5f0e -> idle
info 16:33:33.351: Finished waiting for idle on (kernel): 95bce6e4-e6b0-472f-a846-6c62abde5f0e -> idle
info 16:33:33.355: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/printJupyterDataDir.py
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/pythonFiles/printJupyterDataDir.py
info 16:33:33.357: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 16:33:33.357: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 16:33:33.378: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/Users/bcs/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/tmp/scripts/bec2e75d0c75018bd392f63774ca4ee8a53ccf59a47d59b8b9eba7a1d9b54ba9/jupyter
info 16:38:48.676: Execute Cell 0 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:38:48.677: Execute Cell 1 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:38:48.677: Execute Cell 2 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:38:48.701: Cell 0 executed with state Success
info 16:38:48.759: Cell 1 executed with state Success
info 16:38:48.776: Cell 2 executed with state Success
info 16:44:30.303: Restart requested file:///Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:44:30.304: Restart kernel execution
info 16:44:30.304: Cancel pending cells
info 16:44:30.305: Restarting 95bce6e4-e6b0-472f-a846-6c62abde5f0e
[I 16:44:30.313 NotebookApp] Creating new notebook in 
info 16:44:30.322: installMissingDependencies /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python, ui.disabled=false for resource '/Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb'
info 16:44:30.354: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
info 16:44:30.437: Spec argv[0] updated from '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python' to '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python'
[I 16:44:30.465 NotebookApp] Kernel started: 02435680-b99a-4c6f-9fbd-e9fdefa62486, name: python3914jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99
info 16:44:30.473: Waiting for idle on (kernel): 02435680-b99a-4c6f-9fbd-e9fdefa62486 -> unknown
[W 16:44:30.476 NotebookApp] delete /test-jvsc-dd359b39-f06a-4535-a8a1-fe9e755d928d62b9ed8d-e86f-4e85-b7a5-15f223bd7062.ipynb
info 16:44:30.817: Finished waiting for idle on (kernel): 02435680-b99a-4c6f-9fbd-e9fdefa62486 -> idle
info 16:44:30.818: Got new session 02435680-b99a-4c6f-9fbd-e9fdefa62486
info 16:44:30.818: Started new restart session
info 16:44:30.821: Executing silently Code (idle) = import sys\nprint(sys.executable)
info 16:44:30.823: Widget Message: Received IPyWidgetMessages.IPyWidgets_onRestartKernel
[I 16:44:30.824 NotebookApp] Kernel shutdown: 95bce6e4-e6b0-472f-a846-6c62abde5f0e
info 16:44:30.837: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 16:44:30.837: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 16:44:30.900: Executing silently Code (completed) = import sys\nprint(sys.executable) with 1 output(s)
info 16:44:30.902: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
info 16:44:30.904: UpdateWorkingDirectoryAndPath in Kernel
info 16:44:30.904: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not
info 16:44:30.915: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not with 1 output(s)
info 16:44:30.915: Waiting for idle on (kernel): 02435680-b99a-4c6f-9fbd-e9fdefa62486 -> idle
info 16:44:30.915: Finished waiting for idle on (kernel): 02435680-b99a-4c6f-9fbd-e9fdefa62486 -> idle
info 16:46:3.597: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:46:3.607: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:46:4.91: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 16:46:4.107: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 16:46:4.128: Execute Cell 0 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:46:4.152: Cell 0 executed with state Success
info 16:46:4.680: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46113/7990
info 16:46:4.693: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46113/7990 with 0 output(s)
info 16:47:30.467: Restart requested file:///Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:47:30.467: Restart kernel execution
info 16:47:30.467: Cancel pending cells
info 16:47:30.468: Restarting 02435680-b99a-4c6f-9fbd-e9fdefa62486
[I 16:47:30.479 NotebookApp] Creating new notebook in 
info 16:47:30.489: installMissingDependencies /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python, ui.disabled=false for resource '/Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb'
info 16:47:30.492: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
info 16:47:30.584: Spec argv[0] updated from '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python' to '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python'
[I 16:47:30.607 NotebookApp] Kernel started: 27ec5be6-9239-419e-98e9-7ab7dde63648, name: python3914jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99
info 16:47:30.614: Waiting for idle on (kernel): 27ec5be6-9239-419e-98e9-7ab7dde63648 -> unknown
[W 16:47:30.617 NotebookApp] delete /test-jvsc-854e2d41-a257-4eb8-9acb-556bf1783295afe7b70a-2ad8-425b-b8f8-e2f7e56e3e48.ipynb
info 16:47:30.877: Finished waiting for idle on (kernel): 27ec5be6-9239-419e-98e9-7ab7dde63648 -> idle
info 16:47:30.877: Got new session 27ec5be6-9239-419e-98e9-7ab7dde63648
info 16:47:30.877: Started new restart session
info 16:47:30.880: Executing silently Code (idle) = import sys\nprint(sys.executable)
info 16:47:30.882: Widget Message: Received IPyWidgetMessages.IPyWidgets_onRestartKernel
info 16:47:30.882: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 16:47:30.882: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
[I 16:47:30.882 NotebookApp] Kernel shutdown: 02435680-b99a-4c6f-9fbd-e9fdefa62486
info 16:47:30.945: Executing silently Code (completed) = import sys\nprint(sys.executable) with 1 output(s)
info 16:47:30.947: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
info 16:47:30.947: UpdateWorkingDirectoryAndPath in Kernel
info 16:47:30.947: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not
info 16:47:30.957: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not with 1 output(s)
info 16:47:30.957: Waiting for idle on (kernel): 27ec5be6-9239-419e-98e9-7ab7dde63648 -> idle
info 16:47:30.957: Finished waiting for idle on (kernel): 27ec5be6-9239-419e-98e9-7ab7dde63648 -> idle
[I 16:47:31.880 NotebookApp] Starting buffering for 02435680-b99a-4c6f-9fbd-e9fdefa62486:6d467706-9676-4802-8b3c-2801bc6af15d
info 16:47:53.997: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:47:54.7: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:47:54.315: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 16:47:54.329: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 16:47:54.351: Execute Cell 0 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:47:54.375: Cell 0 executed with state Success
info 16:47:54.917: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46139/7990
info 16:47:54.932: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46139/7990 with 0 output(s)
info 16:47:57.666: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:47:57.677: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:47:57.797: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 16:47:57.807: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 16:47:57.829: Execute Cell 1 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:47:57.917: Cell 1 executed with state Success
info 16:47:58.438: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46139/7990
info 16:47:58.452: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46139/7990 with 0 output(s)
info 16:48:0.964: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:48:0.974: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:48:54.451: Restart requested file:///Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:48:54.451: Restart kernel execution
info 16:48:54.451: Cancel pending cells
info 16:48:54.452: Restarting 27ec5be6-9239-419e-98e9-7ab7dde63648
[I 16:48:54.459 NotebookApp] Creating new notebook in 
info 16:48:54.466: installMissingDependencies /Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python, ui.disabled=false for resource '/Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb'
info 16:48:54.470: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import ipykernel"
info 16:48:54.561: Spec argv[0] updated from '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python' to '/Users/bcs/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python'
[I 16:48:54.584 NotebookApp] Kernel started: 6abb900f-0434-4900-9fe9-f4c17b879127, name: python3914jvsc74a57bd0cba28719ad5162ff832e7a362a3fa3af0cfe9779f395240824868cfb6b757c99
info 16:48:54.590: Waiting for idle on (kernel): 6abb900f-0434-4900-9fe9-f4c17b879127 -> unknown
[W 16:48:54.593 NotebookApp] delete /test-jvsc-7718d7ea-852e-41c1-a932-c97b7f529249cd4e621d-3524-45f9-a99c-6cc555700f2d.ipynb
info 16:48:54.928: Finished waiting for idle on (kernel): 6abb900f-0434-4900-9fe9-f4c17b879127 -> idle
info 16:48:54.929: Got new session 6abb900f-0434-4900-9fe9-f4c17b879127
info 16:48:54.929: Started new restart session
info 16:48:54.932: Executing silently Code (idle) = import sys\nprint(sys.executable)
[I 16:48:54.935 NotebookApp] Kernel shutdown: 27ec5be6-9239-419e-98e9-7ab7dde63648
info 16:48:54.938: Widget Message: Received IPyWidgetMessages.IPyWidgets_onRestartKernel
info 16:48:54.938: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 16:48:54.938: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 16:48:55.0: Executing silently Code (completed) = import sys\nprint(sys.executable) with 1 output(s)
info 16:48:55.2: Process Execution: > ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
> ~/.local/share/virtualenvs/amazonAGI-XQmsfcBC/bin/python -c "import sys;print(sys.executable)"
info 16:48:55.2: UpdateWorkingDirectoryAndPath in Kernel
info 16:48:55.2: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not
info 16:48:55.12: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/bcs/work/experimental/amazonAGI/tuning/whisper"\nif os.getcwd() not with 1 output(s)
info 16:48:55.12: Waiting for idle on (kernel): 6abb900f-0434-4900-9fe9-f4c17b879127 -> idle
info 16:48:55.12: Finished waiting for idle on (kernel): 6abb900f-0434-4900-9fe9-f4c17b879127 -> idle
info 16:49:25.786: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:49:25.795: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:49:26.137: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 16:49:26.152: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 16:49:26.169: Execute Cell 0 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:49:26.192: Cell 0 executed with state Success
info 16:49:26.722: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46158/7990
info 16:49:26.734: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46158/7990 with 0 output(s)
info 16:49:30.579: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:49:30.589: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 16:49:30.720: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 16:49:30.730: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 16:49:30.746: Execute Cell 1 /Users/bcs/work/experimental/amazonAGI/tuning/whisper/test.ipynb
info 16:49:30.837: Cell 1 executed with state Success
info 16:49:31.359: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46158/7990
info 16:49:31.375: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/r4/993b25xn7fq9y36lr77yyc_h0000gn/T/ipykernel_46158/7990 with 0 output(s)
info 16:49:34.752: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 16:49:34.766: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
```

### Coding Language and Runtime Version

Python 3.9.14

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Local

### PR DESCRIPTION
**Pull request by roblourens**
Fix #11546

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]

File: src/notebooks/debugger/helper.ts [hunk 1]
```diff
@@ -15,7 +15,9 @@ export enum IpykernelCheckResult {
 }
 
 export async function isUsingIpykernel6OrLater(kernel: IKernel): Promise<IpykernelCheckResult> {
-    const code = 'import ipykernel\nprint(ipykernel.__version__)';
+    const code = `import builtins
+import ipykernel
+builtins.print(ipykernel.__version__)`;
```
Comment (DonJayamanne) [inline src/notebooks/debugger/helper.ts:20]: @roblourens You could completely get rid of print as well.
```pyhton
import ipykernel
ipykernel.__version__
```

that should be sufficient, as the Python kernel prints the value of the last expression in this case `ipykernel.__version__`, hence a print isn't really necessary

Comment (DonJayamanne) [reply src/notebooks/debugger/helper.ts:20]: though thats an optional change

Comment (roblourens) [reply src/notebooks/debugger/helper.ts:20]: I tried but I'm actually kind of struggling to do that. I get the return result in a different shape and I can't convince TS that the indexing that I have to do is valid... I think I'll leave it this way
