### PR TITLE
don't show python extension install popup when autostarting kernels

### LINKED ISSUE #10011: Python dialog keeps popping up
## Environment data

Jupyter extension: v2022.5.1001341010
Version: 1.68.0-insider (Universal)
Commit: 624bbc4fb966bfa34e9486e320a64a138ac337fd
Date: 2022-05-12T05:20:14.804Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

## Expected behaviour

Dialog should not appear when opening other files

## Actual behaviour

Dialog appears on file load on any notebook file

## Steps to reproduce:

1. open VS Code with a fresh user data directory
2. install jupyter extension
3. open ipynb file, hit run
4. see dialog that asks for python, hit cancel
5. open another notebook file
6. :bug: python dialog keeps appearing for every single python file

https://user-images.githubusercontent.com/35271042/168162475-a096f20d-9796-4ab5-915a-7b2e31ffb518.mp4

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code - Insiders (1.68.0-insider, undefined, desktop)
Jupyter Extension Version: 2022.5.1001341010.
Python Extension not installed.
Workspace folder /Users/miguelsolorio/Developer/notebook
error 13:25:52.260: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=101 uv=1 armv=8 libc=glibc node=16.13.0 electron=17.4.3
    loaded from: /Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/node_modules/zeromq

	at Function.load.path (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/node_modules/zeromq/lib/native.js:1:198)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
	at Function.E._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
	at Function._._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61806)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/node_modules/zeromq/lib/index.js:1:144)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
	at Function.E._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
	at Function._._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61806)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.92747 (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4054444)
	at __webpack_require__ (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4829043)
	at u.zmqSupported (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:552030)
	at u.isSupportedForLocalLaunch (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:551773)
	at u.get isSupported [as isSupported] (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:551683)
	at t.registerTypes (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:565821)
	at /Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4833951
	at /Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4834700
	at /Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4834708
	at e.activate (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:4834830)
	at Function._callActivateOptional (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17470)
	at Function._callActivate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17131)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:14945
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)]
info 13:25:53.367: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb is undefined
info 13:25:53.367: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb with metadata {"interpreter":{"hash":"8dd0a5426ce1a1e5270f81c0823b3a4153d301e47cd2d3a0efaae351cfd9ed2a"},"kernelspec":{"display_name":"Python 3.8.8 64-bit ('base': conda)","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"}} & preferred interpreter 
info 13:25:53.387: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb is undefined
info 13:25:53.412: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb is undefined
info 13:25:53.412: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb with metadata {"interpreter":{"hash":"8dd0a5426ce1a1e5270f81c0823b3a4153d301e47cd2d3a0efaae351cfd9ed2a"},"kernelspec":{"display_name":"Python 3.8.8 64-bit ('base': conda)","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"}} & preferred interpreter 
info 13:25:53.423: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb is undefined
info 13:25:53.425: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-cleaning.ipynb is undefined
info 13:25:58.308: Attempting to start a server because of preload conditions ...
info 13:25:58.325: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb is undefined
info 13:25:58.343: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb is undefined
info 13:25:58.343: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb with metadata {"interpreter":{"hash":"8dd0a5426ce1a1e5270f81c0823b3a4153d301e47cd2d3a0efaae351cfd9ed2a"},"kernelspec":{"display_name":"Python 3.7.3 64-bit","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"},"metadata":{"interpreter":{"hash":"0f3fc1f477b7b6e8a98505e87c3377c352684999b9cf604b9f6bec26ac37c02d"}}} & preferred interpreter 
info 13:25:58.346: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb is undefined
info 13:25:58.372: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb is undefined
info 13:25:58.373: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb with metadata {"interpreter":{"hash":"8dd0a5426ce1a1e5270f81c0823b3a4153d301e47cd2d3a0efaae351cfd9ed2a"},"kernelspec":{"display_name":"Python 3.7.3 64-bit","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"},"metadata":{"interpreter":{"hash":"0f3fc1f477b7b6e8a98505e87c3377c352684999b9cf604b9f6bec26ac37c02d"}}} & preferred interpreter 
info 13:25:58.374: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/data-vizualization.ipynb is undefined
error 13:26:1.288: Error starting server in serverPreload:  [Error: Python extension is not installed
	at f.connect (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:376849)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async y.createServerIfNecessary (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:390016)]
info 13:26:2.411: Attempting to start a server because of preload conditions ...
info 13:26:2.414: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb is undefined
info 13:26:2.426: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb is undefined
info 13:26:2.426: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb with metadata {"interpreter":{"hash":"9ab06bbb6cdc45c1c72e842d27cb0d51721b9b6329506c2ac545da1ac71cc21a"},"kernelspec":{"display_name":"Python 3.9.7 ('main')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"},"orig_nbformat":4} & preferred interpreter 
info 13:26:2.426: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb is undefined
info 13:26:2.441: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb is undefined
info 13:26:2.441: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb with metadata {"interpreter":{"hash":"9ab06bbb6cdc45c1c72e842d27cb0d51721b9b6329506c2ac545da1ac71cc21a"},"kernelspec":{"display_name":"Python 3.9.7 ('main')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"},"orig_nbformat":4} & preferred interpreter 
info 13:26:2.443: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/errors.ipynb is undefined
error 13:26:4.520: Error starting server in serverPreload:  [Error: Python extension is not installed
	at f.connect (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:376849)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async y.createServerIfNecessary (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:390016)]
info 13:26:6.606: Attempting to start a server because of preload conditions ...
info 13:26:6.609: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 13:26:6.686: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 13:26:6.686: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 13:26:6.688: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 13:26:6.697: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 13:26:6.697: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 13:26:6.697: Preferred Remote kernel for Untitled-1.ipynb is undefined
error 13:26:10.519: Error starting server in serverPreload:  [Error: Python extension is not installed
	at f.connect (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:376849)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async y.createServerIfNecessary (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:390016)]
info 13:26:11.214: Attempting to start a server because of preload conditions ...
info 13:26:11.221: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb is undefined
info 13:26:11.254: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb is undefined
info 13:26:11.254: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb with metadata {"interpreter":{"hash":"9ab06bbb6cdc45c1c72e842d27cb0d51721b9b6329506c2ac545da1ac71cc21a"},"kernelspec":{"display_name":"Python 3.9.7 64-bit ('main': conda)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"}} & preferred interpreter 
info 13:26:11.255: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb is undefined
info 13:26:11.270: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb is undefined
info 13:26:11.270: Find preferred kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb with metadata {"interpreter":{"hash":"9ab06bbb6cdc45c1c72e842d27cb0d51721b9b6329506c2ac545da1ac71cc21a"},"kernelspec":{"display_name":"Python 3.9.7 64-bit ('main': conda)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.7"}} & preferred interpreter 
info 13:26:11.271: Preferred Remote kernel for /Users/miguelsolorio/Developer/notebook/lightning.ipynb is undefined
error 13:26:13.409: Error starting server in serverPreload:  [Error: Python extension is not installed
	at f.connect (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:376849)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async y.createServerIfNecessary (/Users/miguelsolorio/code_profiles/empty/extensions/ms-toolsai.jupyter-2022.5.1001341010/out/extension.node.js:2:390016)]

```

</p>
</details>

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #10011

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

File: src/kernels/jupyter/launcher/notebookProvider.ts [hunk 1]
```diff
@@ -53,7 +53,9 @@ export class NotebookProvider implements INotebookProvider {
             return this.jupyterNotebookProvider.connect(options).finally(() => handler.dispose());
         } else {
             handler.dispose();
-            await this.extensionChecker.showPythonExtensionInstallRequiredPrompt();
+            if (!this.startupUi.disableUI) {
```
Comment (IanMatthewHuff) [inline src/kernels/jupyter/launcher/notebookProvider.ts:56]: I have to confess I dug though the history a bit and I'm not sure why this wasn't being seen before? It does require somewhat specific circumstances (disableZMQ, no Python installed) but multiple vscode team members hit it pretty quick.

Comment (IanMatthewHuff) [reply src/kernels/jupyter/launcher/notebookProvider.ts:56]: The issue looks to my eyes like it has been around for quite a while.

**Review by rchiodo — APPROVED** [review]
