### PR TITLE
Match short name paths to full paths for RBL

### LINKED ISSUE #8258: Run by Line debug cell mode just executes the whole cell
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise 21H1
-   Python and/or Anaconda version: Python 3.8.0    Anaconda 2021.05
-   Type of virtual environment used: conda
-   Jupyter server running: N/A

## Expected behaviour

When hitting the Run by Line button on one cell it should execute the cell line by line stopping automatically on every line, indicating the current executed line with a different color and a sign.

## Actual behaviour

When hitting the Run by Line button the cell is executed as if I just pressed the normal Run button (Ctrl + Enter) and the whole cell is executed at once. The button to Continue Execution is shown but the actual line is not marked in any way.

## Steps to reproduce:

1. Open a Jupyter Notebook on VS Code

2. Click on "Run by Line" button on one cell.

Run_by_Line

## Logs

There are no logs for this issue.

### PR DESCRIPTION
**Pull request by roblourens**
Fix #8258

### CODE REVIEW

File: src/client/debugger/jupyter/kernelDebugAdapter.ts [hunk 1]
```diff
@@ -256,6 +257,21 @@ export class KernelDebugAdapter implements DebugAdapter, IKernelDebugAdapter, ID
...
     }
 
+    private lookupCellByLongName(sourcePath: string): NotebookCell | undefined {
+        if (!this.platformService.isWindows) {
+            return undefined;
+        }
+
+        sourcePath = path.normalize(sourcePath);
+        for (let [file, cell] of this.fileToCell.entries()) {
+            if (isShortNamePath(file) && shortNameMatchesLongName(file, sourcePath)) {
```
Comment (DonJayamanne) [inline src/client/debugger/jupyter/kernelDebugAdapter.ts:267]: Oh so we only have issues with short names for cell files.
I thought we had issues with all paths in general.

**Review by DonJayamanne — APPROVED** [review]

File: src/client/debugger/jupyter/kernelDebugAdapter.ts (hunk 1 above)
Comment (roblourens) [reply src/client/debugger/jupyter/kernelDebugAdapter.ts:267]: Where else would you get paths from the kernel? Definitely could be other issues too. I didn't look for anything else.
