### PR TITLE
Check jupyter dependency when throwing jupyter err

### LINKED ISSUE #9271: Attempting to run a cell without Jupyter (non-zmq) will never fail and cells keeps running indefinitely
* I've disabled zmq
* ran a cell,
*  got prompted to select 
* Selected an interpreter from the prompt

Nothing happens, the cell seems to be running for ever (busy)
and there are no error messages displayed, and execution does not stop.

Errors are however logged in the output panel.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #9271

### CODE REVIEW

File: src/client/datascience/errors/errorHandler.ts [hunk 1]
```diff
@@ -104,23 +102,11 @@ export class DataScienceErrorHandler implements IDataScienceErrorHandler {
...
-                    resource,
-                    kernelConnection,
-                    new DisplayOptions(false),
-                    tokenSource.token,
-                    true
-                );
-            } finally {
-                tokenSource.dispose();
-            }
+        } else if (err instanceof JupyterInstallError && (purpose === 'start' || purpose === 'restart')) {
```
Comment (rchiodo) [inline src/client/datascience/errors/errorHandler.ts:105]: Maybe I'm missing something elsewhere, but this will not work for raw. JupyterInstallError is only thrown in the jupyter cases as far as I remember.

**Review by rchiodo — CHANGES_REQUESTED** [review]
Does this work with raw?

File: src/client/datascience/errors/errorHandler.ts (hunk 1 above)
Comment (DonJayamanne) [reply src/client/datascience/errors/errorHandler.ts:105]: I don't see the problem with that, 
If we're dealing with raw, then this error will not be throw, meaning its not a problem

Comment (rchiodo) [reply src/client/datascience/errors/errorHandler.ts:105]: No it means we won't install dependencies into a raw kernel. It will just fail.

Comment (rchiodo) [reply src/client/datascience/errors/errorHandler.ts:105]: That's why it was an 'or' before. It should install dependencies if it's an install error or the dependency analyzer says it needs the dependencies.

Comment (DonJayamanne) [reply src/client/datascience/errors/errorHandler.ts:105]: > No it means we won't install dependencies into a raw kernel. It will just fail.

Aaah, then we need to throw KernelDependency error, i'll check.
The only way we can throw `JupyterInstallError ` is in the case of non-raw, possible we're missing another condition. I'll check

Comment (rchiodo) [reply src/client/datascience/errors/errorHandler.ts]: The code used to check before running a raw kernel but I removed that and had it check here after it failed.

Comment (DonJayamanne) [reply src/client/datascience/errors/errorHandler.ts]: Got it, fixed,

**Review by rchiodo — APPROVED** [review]
