### PR TITLE
Custom test report writer to load test results

### LINKED ISSUE #10389: Web tests output should match node tests output
Web tests are harder to:
- See which tests failed
- Look at the logs

It would be nice if we could unify all of this to look and behave the same.

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #10389

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

File: src/test/web/customReporter.ts [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+        try {
+            error[prop] = JSON.parse(JSON.stringify(err[prop]));
+        } catch {
+            error[prop] = '<..?..>';
+        }
+    });
+    return error as Exception;
+}
+
+function CustomReporter(this: any, runner: mochaTypes.Runner, options: mochaTypes.MochaOptions) {
```
Comment (DonJayamanne) [inline src/test/web/customReporter.ts:120]: Can use ES6 classes, as we cannot import the mocha reporter writers in web, have to use the good old fashioned `require` to import and then extend (again using mocha dependencies to inherit instead of pulling any node specific modules to inherit stuff - as this needs to work in the browser as well).

File: src/test/web/index.ts [hunk 2]
```diff
@@ -47,7 +50,9 @@ export async function activate(context: IExtensionContext): Promise<IExtensionAp
 
             try {
                 // Run the mocha test
-                mocha.run((failures) => {
+                mocha.run(async (failures) => {
+                    // Wait for a while, till we've managed to send the test results to the test server.
+                    await sleep(5_000);
```
Comment (DonJayamanne) [inline src/test/web/index.ts:55]: We only need a few ms, but added 5s, basically we cannot kill VS Code web until all the results have been sent through. I didn't want to complicate the code by adding more checks & locks to determine whether all the data has gone through, this should work 99.9% of the time & keeps the code simple & clean.
