### PR TITLE
format traceback for standalone IW in IPython8

### LINKED ISSUE #10614: Error highlight in Interactive window makes text unreadable in dark mode
the highlight for the undefined value in a NameError is too close to the text color:
image

### PR DESCRIPTION
**Pull request by amunger**
Fixes #10614

We don't have anything stored for generated code in a standalone Interactive Window, but we still need to fix up some formatting for IPython8.

We also don't render links for line numbers in this case, and this PR does not fix that.

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

File: src/interactive-window/outputs/tracebackFormatter.ts [hunk 1]
```diff
@@ -27,20 +27,24 @@ export class InteractiveWindowTracebackFormatter implements ITracebackFormatter
             return traceback;
         }
         const storage = this.storageFactory.get({ notebook: cell.notebook });
-        if (!storage) {
+        const useIPython8Format = traceback.some((traceFrame) => /^[Input|File].*?\n.*/.test(traceFrame));
```
Comment (rebornix) [inline src/interactive-window/outputs/tracebackFormatter.ts:30]: This looks like something we can write unit test for.
