### PR TITLE
Don't use a daemon to launch a kernel anymore

### LINKED ISSUE #1626: VSCode leaves several running processes after exit
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Launch vscode.
2. Open or create a Jupyter Notebook.
3. Do some work on it.
4. Close vscode.
5. Optional: Rinse and repeat.

Expected behavior:

Any processes started by vscode are closed.

Actual behavior:

After launching and closing vscode a few times (and realizing I am starting to run out of memory) I notice this:

```bash
user@laptop:~$ ps aux | grep -v networkd-dispatcher | grep -v unattended | grep -v grep | grep python
user   344513  0.2  0.6 4115828 102040 ?      Sl   May19   3:19 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   345452  0.4  5.3 5162548 858400 ?      Sl   May19   5:46 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   345607  0.2  0.6 4443632 102484 ?      Sl   May19   3:01 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   353204  0.2  0.6 3788220 105468 ?      Sl   May19   1:55 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   353605  0.0  0.2 117072 46508 ?        S    May19   0:01 /usr/bin/python3 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
user   353771  0.3  0.6 3796468 105576 ?      Sl   May19   2:29 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   353933  0.2  0.2 3722708 39000 ?       Sl   May19   1:31 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   354840  0.2  0.2 3796424 35728 ?       Sl   00:35   1:34 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   355331  0.9  5.4 6179224 869260 ?      Sl   00:39   6:06 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   356104  0.3  0.6 3862044 111216 ?      Sl   00:52   1:52 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   366116  1.6  0.4 3796252 76032 ?       Sl   10:27   0:35 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   366803  2.3  0.4 1007044 69596 ?       Sl   10:32   0:44 /usr/bin/python3 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
user   366808 10.1  5.4 5509256 871684 ?      Sl   10:32   3:16 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/languageServer.0.5.50/Microsoft.Python.LanguageServer
user   366831  0.0  0.2 551048 35328 ?        Ssl  10:32   0:01 /usr/bin/python3 -m ipykernel_launcher -f /home/user/.local/share/jupyter/runtime/kernel-33b1ca6c-b09c-41dd-b2fc-c466b2511581.json
user   366855  0.0  0.2 550640 35408 ?        Ssl  10:32   0:01 /usr/bin/python3 -m ipykernel_launcher -f /home/user/.local/share/jupyter/runtime/kernel-a5a7d55e-0ebc-4b4b-aac4-4d1dddff8450.json
user   368190  7.6  1.2 2471816 200372 ?      Ssl  10:45   1:27 /usr/bin/python3 -m ipykernel_launcher -f /home/user/.local/share/jupyter/runtime/kernel-b00685be-189e-4f07-80e0-237ab6772827.json
user   368212  0.0  0.2 550648 43728 ?        Ssl  10:45   0:00 /usr/bin/python3 -m ipykernel_launcher -f /home/user/.local/share/jupyter/runtime/kernel-918a11e0-f81e-4740-a3c1-e5d5ca074570.json
user   369055  4.4  1.3 2076996 219232 pts/0  Sl+  10:57   0:19 /usr/bin/python3 /home/user/.local/bin/ipython
user   369168  2.0  0.3 709300 62112 ?        Sl   10:58   0:08 /usr/bin/python3 /home/user/.vscode-oss/extensions/ms-python.python-2020.5.80290/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
user@laptop:~$ 
```

Extension version: 2020.5.80290
VS Code version: Code - OSS 1.46.0 (3984852b33bd6897dd83108ac305c567d49e8fda, 2020-05-15T14:46:12.527Z)
OS version: Linux x64 5.4.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1137)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.23GB (0.93GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

### PR DESCRIPTION
**Pull request by rchiodo**
Fixes #1626

Daemon was necessary before to speedup environment acquisition. Since this is all cached now, doesn't make a difference.

Daemon was causing problems on shutdown because it would be killed before it could send the SIGTERM to the child kernel process.

Now we create the kernel process directly so that VS code will kill it.

### CODE REVIEW

File: src/client/datascience/kernel-launcher/kernelProcess.ts [hunk 1]
```diff
@@ -395,72 +385,41 @@ export class KernelProcess implements IKernelProcess {
     private async launchAsObservable(workingDirectory: string, @ignoreLogging() cancelToken: CancellationToken) {
         let exeObs: ObservableExecutionResult<string> | undefined;
 
-        // Use a daemon only if the python extension is available. It requires the active interpreter
-        if (
```
Comment (rchiodo) [inline src/client/datascience/kernel-launcher/kernelProcess.ts:399]: This whole change is just removing this if condition. This ripples up because we don't use a daemon in launching anymore.

File: src/client/datascience/kernel-launcher/kernelProcess.ts [hunk 2]
```diff
@@ -395,72 +385,41 @@ export class KernelProcess implements IKernelProcess {
...
+        // The first argument is sliced because it is the executable command.
+        const args = this.launchKernelSpec.argv.slice(1).map((a) => {
+            // Some kernel specs (non-python) can have argv as `--connection-file={connection_file}`
+            // The `connection-file` will be quoted when we update it with the real path.
+            if (a.includes('--connection-file')) {
+                return a;
             }
-            if (cancelToken.isCancellationRequested) {
-                throw new CancellationError();
+            if (a.includes(' ')) {
```
Comment (DonJayamanne) [inline src/client/datascience/kernel-launcher/kernelProcess.ts:414]: Is this correct, would be good to create an issue (& close as part of this PR) so we know what scneario this was fixing.

**Review by DonJayamanne — APPROVED** [review]

File: src/client/datascience/kernel-launcher/kernelProcess.ts (hunk 2 above)
Comment (rchiodo) [reply src/client/datascience/kernel-launcher/kernelProcess.ts:414]: I didn't change this code. It was already there.

Comment (DonJayamanne) [reply src/client/datascience/kernel-launcher/kernelProcess.ts:414]: Oops, sorry
3 weeks away and I can't read diffs anymore!!

**Review by IanMatthewHuff — CHANGES_REQUESTED** [review]
Looking it up more now, but shouldn't we have a fair bit more dead code from this change? Like kernelDaemonPreWarmer and stuff? Would be good to remove that along with this, unless it has a use I'm not thinking of.

File: src/client/datascience/kernel-launcher/kernelProcess.ts [hunk 3]
```diff
@@ -395,72 +385,41 @@ export class KernelProcess implements IKernelProcess {
...
-                // The `connection-file` will be quoted when we update it with the real path.
-                if (a.includes('--connection-file')) {
-                    return a;
-                }
-                if (a.includes(' ')) {
-                    return `"${a}"`;
-                }
-                return a;
-            });
-            exeObs = executionService.execObservable(executable, args, {
```
[the remark this answers is not in the document]
Comment (IanMatthewHuff) [reply src/client/datascience/kernel-launcher/kernelProcess.ts:459]: Yeah, we needed it at the time, but it just added a big layer of complexity around launch. Nice to remove it.

**Comment by rchiodo** [comment]
Yeah I should remove the kernelDaemonPrewarmer too.

File: src/client/datascience/kernel-launcher/kernelProcess.ts [hunk 4]
```diff
@@ -401,26 +384,31 @@ export class KernelProcess implements IKernelProcess {
...
-                this.resource,
-                workingDirectory,
-                this.launchKernelSpec,
-                this._kernelConnectionMetadata.interpreter
-            );
-            if (this.disposed || cancelToken.isCancellationRequested) {
-                kernelDaemonLaunch.daemon?.dispose();
-                kernelDaemonLaunch.observableOutput.dispose();
-            }
+            const executionServicePromise = this.pythonExecFactory.createActivatedEnvironment({
```
Comment (rchiodo) [inline src/client/datascience/kernel-launcher/kernelProcess.ts:387]: I switched this to do what happens if daemon support is turned off.

Comment (rchiodo) [reply src/client/datascience/kernel-launcher/kernelProcess.ts:387]: Instead of just doing what we do for non python kernels.

**Review by IanMatthewHuff — APPROVED** [review]
