### PR TITLE
Port changes from main branch to remove diagnostic feature

### LINKED ISSUE #11040: File shadowing warning given on __init__.py file
Type: <b>Bug</b>

I have an app where I have an __init__.py file  that contains only `__version__ = '0.1.0'`. But opening it in VS Code is giving me the file name shadowing warning from Jupyter:

image

I think the chances of someone creating a file called __init__.py for their file is really small (compared to e.g. random.py, math.py), so I think files that start with __ shouldn't have this warning triggered for them? 

 Extension version: 2022.8.1002161046
VS Code version: Code - Insiders 1.70.0-insider (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-03T05:53:23.899Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (1.32GB free)|
|Process Argv|--crash-reporter-id 664528d7-58ad-4032-9a86-c163f8ada97b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728

```

</details>

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #11040

### CODE REVIEW

File: src/platform/interpreter/constants.ts [hunk 1]
```diff
@@ -6,397 +6,222 @@ export const JupyterKernelStartFailureOverrideReservedName =
...
-    'abc',
-    'abs',
-    'aifc',
-    'all',
-    'antigravity',
-    'any',
-    'argparse',
-    'array',
-    'ascii',
+    // 'abc',
```
Comment (rchiodo) [inline src/platform/interpreter/constants.ts:16]: Shouldn't we put these back now that the diagnostic is turned off? Otherwise we're guessing here that these modules are okay to override in a kernel situation.

Comment (DonJayamanne) [reply src/platform/interpreter/constants.ts:16]: Sure thing

**Review by amunger — APPROVED** [review]

File: src/platform/interpreter/constants.ts (hunk 1 above)
Comment (DonJayamanne) [reply src/platform/interpreter/constants.ts]: & agreed

File: src/platform/interpreter/constants.ts [hunk 2]
```diff
@@ -299,54 +146,40 @@ export const BuiltInModules = [
...
     'shutil',
     'signal',
     'site',
-    'slice',
     'smtpd',
     'smtplib',
     'sndhdr',
     'socket',
     'socketserver',
-    'sorted',
```
Comment (rchiodo) [inline src/platform/interpreter/constants.ts:332]: I would have thought these would all be back?

**Review by amunger — APPROVED** [review]

File: src/platform/interpreter/constants.ts (hunk 2 above)
Comment (DonJayamanne) [reply src/platform/interpreter/constants.ts:332]: No, those are not modules that can be imported, they are reserved names like functions/classes etc.
E.g. `eval` and `AssertionError` are classes, and we know these cannot be imported.
The error message focuses on modules that can be imported by python and override pacakges.
Even if you have such a file, python will not end up using them, unless we have it in a startup file that gets pulled into the python runtime that loads them and shadows the built ins

**Review by rchiodo — APPROVED** [review]

File: src/platform/interpreter/constants.ts (hunk 2 above)
Comment (amunger) [reply src/platform/interpreter/constants.ts:332]: If it's more likely they'd create false positives than actually catch something - better to leave them out, but maybe there was a way they could still interfere? I didn't quite understand the levels of uncertainty about the files
