### PR TITLE
Fix open in data viewer

### LINKED ISSUE #10007: View in Data Viewer No Longer Working
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Trying to debug a pandas dataframe and "View in Data Viewer" is no longer working. I've tried updating everything to the latest and still get the below error.

image

### VS Code Version

Version: 1.67.1 (user setup) Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d Date: 2022-05-06T12:37:03.389Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

 v2022.4.1011282140

### Jupyter logs

```shell
warn 11:52:46.89: DataScience Error [TypeError: s.replace is not a function
	at Function.file (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:18545)
	at x.onVariablePanelShowDataViewerRequest (c:\Users\vf941d\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:57846)
	at x.<anonymous> (c:\Users\vf941d\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:722769)
	at o._executeContributedCommand (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:31333)
	at o.$executeContributedCommand (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:32037)
	at s._doInvokeHandler (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13828)
	at s._invokeHandler (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:13512)
	at s._receiveRequest (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:10843)
	at c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:8949
	at m.invoke (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at l.fire (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19001)
	at c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:34426
	at m.invoke (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at l.fire (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19001)
	at r._receiveMessage (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23582)
	at c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21116
	at m.invoke (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at v.acceptChunk (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15832)
	at c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14962
	at Socket.R (c:\Users\vf941d\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13798)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)]
```

### Coding Language and Runtime Version

Python v3.8.3

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Local

### PR DESCRIPTION
**Pull request by IanMatthewHuff**
Fixes #10007 and #10012

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [x] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [x] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for feature-requests.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

### CODE REVIEW

**Review by DonJayamanne — APPROVED** [review]

File: src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts [hunk 1]
```diff
@@ -136,4 +123,39 @@ export class DataViewerCommandRegistry implements IExtensionSingleActivationServ
             }
         }
     }
+
+    // For the given debug adapter, return the PythonEnvironment used to launch it
+    // Mirrors the logic from Python extension here:
+    // https://github.com/microsoft/vscode-python/blob/35b813f37d1ceec547277180e3aa07bd24d86f89/src/client/debugger/extension/adapter/factory.ts#L116
+    private async getDebugAdapterPython(
```
Comment (DonJayamanne) [inline src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:130]: Is it possible to have some kind of test to ensure we don't break again,
E.g. a debugger test that verifies this part.
The problem is this isn't an API contract, hence Python extension can change this anytime & we'd break again & the only way we'd know about this breakage is when a user reports it

**Review by rchiodo — APPROVED** [review]

File: src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts (hunk 1 above)
Comment (IanMatthewHuff) [reply src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:130]: Yeah, taking a peek at that now. At a minimum I could verify the debug configuration looks as expected (not sure yet on how I would best trigger the context menu command).

@DonJayamanne Questions for ya, since I don't think that I've ever added anything to it. Should I maybe just talk to the python team and just expose this in the API?

Comment (DonJayamanne) [reply src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:130]: Don't see any harm in that, though it feels like an API for this might be overkill.

Comment (DonJayamanne) [reply src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:130]: This wouldn't be a problem if the debugger was part of the python extension 😉

Comment (IanMatthewHuff) [reply src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts:130]: Yeah, I feel like we have a few areas like that, "light" python dependencies. I added a full stack test here (up to opening the data viewer) that should help to cover this. I don't think that we had testing for any of this scenario before.

**Comment by IanMatthewHuff** [comment]
> I assume the linter will fail here. At least I hope so: 'test.only'

@rchiodo Yup, it's on purpose though. Test.only still works for when I want to run only my new test on CI. Easier than grep for getting logs and screenshots for just one test on CI. I'll remove it once I have the test fixed up on CI.
